### ISSUE TITLE
Pitch Bend only on MIDI channel 1 ?

### ISSUE THREAD

**Issue by keymanpal** [asb2m10/dexed#100]
If you send Pitch Bend Messages on any MIDI channel other then 1, nothing happens.
Love DEXED! but this is a show stopper in a multi-instance setup (channel per note)
Checked using AB Live 9.7.1 and GigPerformer 1.6.6

**Comment by asb2m10** [comment]
Agreed, since it listens to any notes, there is no reason to filter the pitch bend message. Will be fixed in the next version.

**Comment by keymanpal** [comment]
Great to know!! can't wait for next version ;-)
