### ISSUE TITLE
VST Dexed Ableton Live 9 Lite on Mac OS 10.12 Sierra issue

### ISSUE THREAD

**Issue by SamHep0803** [asb2m10/dexed#101]
Explained most of it in the title,

I ran `cd ~/Library/Audio/Plug-Ins/VST/Dexed.vst/Contents/MacOS` and `otool -L Dexed` in Terminal and I got this: https://pastebin.com/i8vAVZDA

I've tried downgrading my Ableton to 32x bit that didn't work. I tried using wine to run savihost that also didn't work but I think that was a wine issue.

Oh, and I'm pretty sure it has nothing to do with Ableton 9 Lite because I have another VST working in Ableton.

Many Thanks, Sam

**Comment by SamHep0803** [comment]
And I've got a picture of what the error box is in Ableton: http://imgur.com/a/eR6gv

**Comment by asb2m10** [comment]
Sorry for the late reply, I just got this idea... This could be a gatekeeper issue with 10.12 ; what does this return ?

$ cd ~/Library/Audio/Plug-Ins/VST
$ spctl -a -t exec -vv Dexed.vst
