### ISSUE TITLE
0.9.3 PITCH EG LEVEL automation bug

### ISSUE THREAD

**Issue by N871** [asb2m10/dexed#103]
I'm using Dexed 0.9.3 in Max Msp 7 on a mac.

I'm sending parameter messages to the dexed vst to control it.
Everything works fine except for the following parameters:

-PITCH EG LEVEL 2
-PITCH EG LEVEL 3
-PITCH EG LEVEL 4

All of them have the same parameter name ("PITCH EG LEVEL") and can't therefor be controlled separately. I hope this can be fixed because it's really the only thing that is somewhat bugging me. Great vst!

**Comment by asb2m10** [comment]
This might be an issue with Max/MSP 7 since with version 8 I am able to automate those settings without any issues.
