### ISSUE TITLE
The AU component is not recognized

### ISSUE THREAD

**Issue by garbi** [asb2m10/dexed#104]
On macOS High Sierra 10.13, the AU version of Dexed is not recognized as AU plugin by Logic Pro X (10.3.2) nor by GarageBand (10.2.0) when installed in /Library/Audio/Plug-Ins/Components or in ~/Library/Audio/Plug-Ins/Components. The VST version works however okay in Reason (9.5.2d21 build 8636).

**Comment by fluffy-critter** [comment]
I am having this issue as well. Are there any logs that might be useful? When I installed the .component file, Logic notified me that it was scanning AUs for compatibility, but didn't provide me any sort of report at the end and I'm not finding any logs.

The VSTi is appearing just fine in Reaper.

**Comment by asb2m10** [comment]
Could be extra "security" validation added in 10.13. Sadly, my main Mac stays on 10.10 for compatibility reasons. Can you run this on the command line: 

$ auval -v aumu Dexd DGSB

**Comment by fluffy-critter** [comment]
```windowlick[~] fluffy$ auval -v aumu Dexd DGSB

    AU Validation Tool
    Version: 1.6.1a1 
    Copyright 2003-2013, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aumu' - 'Dexd' - 'DGSB'
--------------------------------------------------
ERROR: Cannot get Component's Name strings
ERROR: Error from retrieving Component Version: -50

* * FAIL
--------------------------------------------------
TESTING OPEN TIMES:
FATAL ERROR: didn't find the component
```

I doubt it's a security/signing issue since other free/cheap third-party AUs continue to work for me even in 10.13.

I note that `auval -a` does not list anything regarding Dexed.

**Comment by fluffy-critter** [comment]
I just looked at the `Dexed.component/Contents/Info.plist` and it appears to be missing its entire `AudioComponents` section, which probably has something to do with it. :)

**Comment by asb2m10** [comment]
For the next version of dexed, I had to drop 10.7 support... the next version will be based on 10.8 SDK and it does contains the AudioComponents section in the Info.plist.

Test this build to see if it works : http://le-son666.com/software/dexed/DexedSDK10.8.zip
PS: this is a debug build and generates logs...

**Comment by fluffy-critter** [comment]
Nope, that build doesn't appear either. I also tried deleting my AudioUnit cache in `$HOME/Caches/AudioUnit` before starting Logic and that didn't help.

**Comment by chrisstr** [comment]
I've had the same issue with Logic not recognizing the plugin. 

After removing the file `~/Library/Caches/AudioUnitCache/com.apple.audiounits.cache` and rebooting the system afterwards, Logic found Dexed upon its next launch. The `Dexed.component` file was in the `Components` folder during that process. 

(macOS High Sierra 10.13.1, Logic Pro X 10.3.2)

**Comment by perlmunger** [comment]
I did the same as @chrisstr and it worked for me as well--using the plugin in the main zip file not the debug one that @asb2m10 posted.

**Comment by fluffy-critter** [comment]
Ah, I just revisited this again, and simply doing what @chrisstr did worked for me. Thanks!

**Comment by asb2m10** [comment]
Thanks @chrisstr , I think it's time that I make an OS X installer and this time I will flush the audiounits cache when then installer is ran.

**Comment by ichthyoidoc** [comment]
I'm having a similar problem. Logic 10.4 with dexed version 0.9.3. I tried the solutions above but they haven't worked.

**Comment by asb2m10** [comment]
@ichthyoidoc , can you try this on the prompt and return the results : 

$ cd /Library/Audio/Plug-Ins/Components
$ spctl -a -t exec -vv Dexed.component

**Comment by ichthyoidoc** [comment]
here are my results: Dexed.component: accepted
override=security disabled

After resetting all my plug-ins again and restarting again, Dexed is now read through Logic 10.4. I've been having similar problems with Logic 10.4 with other plug-ins though. Each time, I've had to reset all my plug-ins again and rescan. Sometimes more than once. Could be a problem with Logic. Thanks for the help! Glad I can get into Dexed now!
