### ISSUE TITLE
Windows Logic 5.5.1 Support

### ISSUE THREAD

**Issue by MMHook** [asb2m10/dexed#105]
Hi
I've installed Dexed in Logic 5.5.1 on pc.  The vst plugin opens fine but I'm not getting any sound from it.  I haven't found any threads on this so wondered if anyone has any suggestions I can try.  Other vsts work fine in my set up.  Dexed appears under the stereo vst folder in audio instruments.  Any help much appreciated...

**Comment by asb2m10** [comment]
Sorry, we cannot support a DAW that was release more than 10 years ago.
