### ISSUE TITLE
Pitch EG - can't get it to be quick enough

### ISSUE THREAD

**Issue by unfa** [asb2m10/dexed#108]
When trying to make drum sounds with Dexed, I that the Pitch EG creates a rather slow pitch ramp even when I'm using the fastest possible Rate values for the controls points.

I'd expect just a click, but this makes a long pitch slide instead:
![selection_064](https://user-images.githubusercontent.com/491704/31679788-87db2f4a-b372-11e7-8fad-7047e0c4bd53.png)

I can't get a fast pitch ramp with this, which is strange becaue other EGs allow me to make short AD type bursts.

Am I doing something wrong? Or maybe DX7 worked this way and it's meant to be like that?

**Comment by Sentinel77** [comment]
Hi,

 I compared this with the Yamaha DX7 and it sounds the same.

Using a smaller pitch change, with 'P EG level' values closer to the defaults will have a faster attack.
