### ISSUE TITLE
All Notes Off / All Sound Off

### ISSUE THREAD

**Issue by rd--** [asb2m10/dexed#110]
Hello, Thanks for Dexed, it's amazing! I think the "All Notes Off" (CC=123/0x7B) handling is odd? It behaves more like "All Sound Off" (ie. CC=120/0x78) ? Some keyboards (ie, from Roland, ie the D-50) send "All Notes Off" messages whenever the last remaining held key is released (ie. very often).  This change makes Dexed unplayable from these instruments.  Could L308 below be changed from 123 to 120? The logic for 123 is a little more involved I guess, it should release any open notes in the "usual" way.  The description at the midi-cc-list table below is I think quite clear about this. Best, rd

- https://github.com/asb2m10/dexed/issues/72
- https://github.com/asb2m10/dexed/blob/master/Source/PluginProcessor.cpp#L308
- http://nickfever.com/music/midi-cc-list

MIDI CC120 | All Sound Off | Mutes all sounding notes. It does so regardless of release time or sustain. 

MIDI CC123 | All Notes Off | Mutes all sounding notes. Release time will still be maintained, and notes held by sustain will not turn off until sustain pedal is depressed.

**Comment by asb2m10** [comment]
Yes, this will definitely be implemented in the next version.
