### ISSUE TITLE
HELP PLEASE PASCAL!!! 

### ISSUE THREAD

**Issue by jonryman** [asb2m10/dexed#111]
ok, so im actually an end user. NOT a programmer in any way. Unless you count the DMX. Im a known producer doing a supercharged "80s" influenced project. which is where DEXED comes into the picture. I HAVE to use mac 10.6.8 for a whole F$%Kton of reasons i wont bore you with now. I know other users have had a few issues and i know you have directed them to 0.9. I HAVE GOT TO GET THIS WORKING! here is the retarded validation message:
alidating Audio Unit Dexed by Digital Suburban:

  * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
         AU Validation Tool
         Version: 1.6.1a1 
          Copyright 2003-2007, Apple, Inc. All Rights Reserved.

         Specify -h (-help) for command options
  * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aumu' - 'Dexd' - 'DGSB'
--------------------------------------------------
Manufacturer String: Digital Suburban
AudioUnit name: Dexed
Component Version: 1.0.0 (0x10000)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
2017-12-05 14:08:04.746 auvaltool[195:a07] Error loading /Users/jonathanpratt/Library/Audio/Plug-Ins/Components/Dexed.component/Contents/MacOS/Dexed:  dlopen(/Users/jonathanpratt/Library/Audio/Plug-Ins/Components/Dexed.component/Contents/MacOS/Dexed, 262): Symbol not found: __tlv_bootstrap
  Referenced from: /Users/jonathanpratt/Library/Audio/Plug-Ins/Components/Dexed.component/Contents/MacOS/Dexed
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/jonathanpratt/Library/Audio/Plug-Ins/Components/Dexed.component/Contents/MacOS/Dexed
FATAL ERROR: OpenAComponent: result: -50,0xFFFFFFCE

validation result: couldn't be opened

I have messaged you before basically saying if you can help us out i will more will than willing to donate££$£$. Spent hours on this and really really wanna test this awesome synth you have made!!

**Comment by asb2m10** [comment]
Does the version 0.9.0 work ?

http://le-son666.com/software/dexed/dexed-0.9.0-osx.zip ; it should...

**Comment by jonryman** [comment]
awesome for getting in touch...
i have become obsessed with getting this to run.
i know its a dope dx7.
so...
im pretty sure i've tried this but im gonna try again.
i sent you the stupid validation notice that logic providess upon trying to run for the first time.
lets try this again and see what happens.
bear with me..
and thanks again for providing this synth and your response...!
jonee
--------------------------------------------
On Fri, 8/12/17, Pascal Gauthier <notifications@github.com> wrote:

 Subject: Re: [asb2m10/dexed] HELP PLEASE PASCAL!!! (#111)
 To: "asb2m10/dexed" <dexed@noreply.github.com>
 Cc: "jon ryman" <interloper67@yahoo.co.uk>, "Author" <author@noreply.github.com>
 Date: Friday, 8 December, 2017, 3:44
 
 Does the version 0.9.0 work ?
 

 ; it should...
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by jonryman** [comment]
ok....
so just tried it again. nothing visible. same with version 0.9.1
does that validation notice tell you anything?
is it possible to get the VST version up and working.
just doing the same as per norm.
component into the components lib/user etc etc along with all the other components.
being a paranoid $£$% I rechecked my OS. its 10.6.8
before apple went and f$%cked so many things!
anyways....appreciate any help here!
kindest regards,
jon
--------------------------------------------
On Fri, 8/12/17, Pascal Gauthier <notifications@github.com> wrote:

 Subject: Re: [asb2m10/dexed] HELP PLEASE PASCAL!!! (#111)
 To: "asb2m10/dexed" <dexed@noreply.github.com>
 Cc: "jon ryman" <interloper67@yahoo.co.uk>, "Author" <author@noreply.github.com>
 Date: Friday, 8 December, 2017, 3:44
 
 Does the version 0.9.0 work ?
 http://le-son666.com/software/dexed/dexed-0.9.0-osx.zip
 ; it should...
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
