### ISSUE TITLE
Dexed 0.9.3 vst non funziona con digital performer 8.07

### ISSUE THREAD

**Issue by Frankati** [asb2m10/dexed#112]
Hi, I recently had to replace my old mac with a new pc with Windows 10.
Among the software plugins that I still want to use there is obviously also the Dexed (it's really amazing !!!).
My DAW software that I use is MOTU Digital Performer 8.07 and DEXED 0.9.2 and 0.9.3 as AU plugin on the Mac works perfectly. But I've found that as a VST plugin DEXED 0.9.3 and 0.9.2 do not work on OSX or Windows.

In fact, the "VST examination" of DP8 fails and the following window reports "1 had serious problems and will not be loaded".

Testing the VST with Cantabile the plugin works correctly, so it is clear that there is a problem in DP8, but a friend of mine told me that DEXED 0.9.0 worked properly with DP8 on the PC (therefore in VST format).

I have tried previous versions of DEXED on the web, but I only found 0.9.3.
Is it possible to have the installer of the 0.9.0 (possibly also of the 0.9.1 to try)?
What other solutions can I try without having to change DAW?

**Comment by asb2m10** [comment]
This is a probably a build issue; I have upgraded my Windows machine and this time will use different build tool for 0.9.4. I will update this issue and ask you if the new build works.

**Comment by asb2m10** [comment]
I've just release the beta for 0.9.4; please try this one to see if you have the same issue....

https://github.com/asb2m10/dexed/releases/tag/v0.9.4
