### ISSUE TITLE
24 engine ignores  feedback operator in algo  6

### ISSUE THREAD

**Issue by gentleclockdivider** [asb2m10/dexed#115]
This bug concerns algo 5 and 6 , differences between engine type ( mark 1 versus modern ) .

Algoritm 5 : only operator 6 is feedback enabled .
Algoritm 6: is output of carrier 5 back to modulator 6 which in turns goes into 5 ..thus both operators are part of the feedback loop 

Both algorimts have a different character when feedback is enabled ..
Now the bug .

The bug is when dexed is set to 24 bit engine option , algoritm 6 is treated the same as algoritm 5 ., you can clearly hear this when switching algoritms , engine type .
In 24 bit algo 6 , is completely ignoring the feedback going from 5 back --> 6

The engine settings should have no effect on the algoritm settings ., recreating both algo's in an fm synth like fm7/fm8 or sytrus ...both algoritms have different character . 

And this should be the case with dexed too when switching engines .
On the dexed site , the creator states that the engine type also has an influence on the bit depth of the sine waves and the amplitude scales , this should be no reason why the modern engine ignores a feedback opera-tor .
Other F.M. synths do it correctly

Link to sound file 
https://app.box.com/s/qk248k3llx8cbqu8ommuwn9zmoysc0ij
And link to screenshot of algo 6

**Comment by gentleclockdivider** [comment]
Screenshot for algo 6

**Comment by gentleclockdivider** [comment]
Screenshot for algo 6

https://i.imgur.com/sKM89U7.jpg

**Comment by asb2m10** [comment]
The 24-bit engine is a copy of [msfa](https://github.com/raphlinus/music-synthesizer-for-android-old) that didn't implement the complete feedback for algo 4 and 6. It is kept as-is to be a baseline inDexed. I don't plan updating the msfa engine since it is a reference implementation.
