### ISSUE TITLE
sending sysex voice bulk data to Dexed results in operators being "randomly" turned on and off

### ISSUE THREAD

**Issue by jeremybernstein** [asb2m10/dexed#126]
I was experimenting with using Dexed as the target of an external editor. I discovered that sending voice data to Dexed caused operators to randomly turn on and off. Turns out that the checksum byte (data byte 155) was being used for this (parameter change 155 (group = 0, subgroup = 1, parameter = 27) handles this, but that data isn't included in a bulk dump.

**Comment by asb2m10** [comment]
Based on the documentation
