### ISSUE TITLE
High CPU usage for the User Interface

### ISSUE THREAD

**Issue by jeremybernstein** [asb2m10/dexed#128]
I'm seeing something like 25% of 1 CPU on an older, but Core i7-based, Macbook Pro. I've made some changes locally which help with this a lot, but there's still too much painting going on. I'll send over a pull request after I've had a chance to clean it up.

**Comment by asb2m10** [comment]
Oh yes, the UI code, especially for the refresh is not optimized. Jule from JUCE is really really against image overlays for controls (like VUs).

I was thinking about putting the efforts on the next version (0.9.5), where efforts would be done for UI scaling and maybe use GL for graphics update that would off load the CPU.

But anything that could optimize this would be great. Thanks.

**Comment by asb2m10** [comment]
The CPU usage is related to the VU meter based on image rendering. It got worst once we got to 2x rendering. This is now dexed top priority.
