### ISSUE TITLE
macOS installer VST location replacement

### ISSUE THREAD

**Issue by jasonnolan** [asb2m10/dexed#129]
hi Pascal;

Thanks for the update to 0.9.4b1. Standalone is fine, andI noticed that the Dexed.component is updated in the correct directory, but the Dexed.vst plugin didn't seem to update. Is there any way to confirm the VST version? Since there's no options button as on the standalone (which gives the version), it's not clear what to do. Don't want to be testing the wrong version.

I'm running the VST in Ableton Live on a mac OSX 10.12

Cheers.

**Comment by techieMusician** [comment]
I also think this needs to be looked into. I am able to open the standalone program on linux but when I copy over Dexed.so into my /usr/lib/vst/ it is not being recognized by any of my vst plugin hosts. (ardour or carla)

**Comment by asb2m10** [comment]
@jasonnolan , just click on the "dexed" logo, you will see the about box with the current version. 

@techieMusician , please open another issue for this since it is not related. Also, try it with JUCE PluginHost to see if you have the same issue.

**Comment by jasonnolan** [comment]
thanks. is there a wiki or something where we can add this info for the next noob like me who comes by?

**Comment by asb2m10** [comment]
Hi @jasonnolan , collaboration are welcomed for sure :) (the wiki is public). Please tell me if you have any issue since I cannot test this.

**Comment by asb2m10** [comment]
The OS X installer cannot confirm the component version when it is updated since it was installed manually; it seems that I cannot force this. 

Dexed documentation now mention that you have to remove the VST or component file before running the installer.
