### ISSUE TITLE
JACK support for standalone version?

### ISSUE THREAD

**Issue by SpotlightKid** [asb2m10/dexed#131]
Is there an option to build the standalone version with JACK audio output and MIDI input support?

If not, would it be possible to add this?

**Comment by asb2m10** [comment]
I tend to put minimal dependencies on dexed to simplify it's build... but it should be doable if you configure JUCE to support it :

1. Download JUCE https://github.com/WeAreROLI/JUCE/archive/5.2.1.tar.gz (for dexed 0.9.4) and untar it 
2. Modify file extras/Projucer/JuceLibraryCode/AppConfig.h to change 
`#define JUCER_ENABLE_GPL_MODE 1`
3. Build ProJucer in extras/Projucer/Builds/LinuxMakefile
4. Execute ProJucer and open Dexed.jucer
5. Select Modules -> juce_audio_devices and enable JUCE_JACK
6. Save Project and rerun Dexed build. 

Let me know if this works....

**Comment by SpotlightKid** [comment]
Yes, works as you described. Thanks!

Now I need to find a way to bake these changes into the Arch AUR package build process...

**Comment by SpotlightKid** [comment]
> Now I need to find a way to bake these changes into the Arch AUR package build process...

Well, that was surprisingly easy:

    sed -i -e 's|JUCE_JACK="0"|JUCE_JACK="1"|' Dexed.jucer
    Projucer --resave Dexed.jucer

:)

See https://aur.archlinux.org/packages/dexed-git/
