### ISSUE TITLE
Dexed 0.9.4 not compatible with WindowsXP

### ISSUE THREAD

**Issue by E-Gwen** [asb2m10/dexed#133]
Hi,

I was making some tests with Dexed 0.9.3 through Carla 2.0.0-beta6, Ardour 5.12, and through Mixbus 4.3, but when I upgrade to 0.9.4 version of Dexed, no more .dll plugin appears.

The installer works well, but came with no result.

Maybe a path problem with Microsoft Windows XP 32 Bits, which is the latest one to use C:\Program Files instead of C:\Program ?

Fixing this issue will be very useful for my MIDI tests !
Thank you by advance.

Best regards.

E-Gwen.

**Comment by asb2m10** [comment]
Hi, 

Are you able to open the standalone version (.exe), if not, this means it is a build/library issue.

**Comment by E-Gwen** [comment]
Well, the binary is being installed, but when I run the .exe application, I get this message : 

"C:\Program Files\Dexed\Dexed.exe n'est pas une application Win32 valide"

"C:\Program Files\Dexed\Dexed.exe is not a Win32 valid application"

So, I'm NOT able to open the standalone version...

**Comment by papwalker** [comment]
Reinstall, untick 64bit options.

**Comment by asb2m10** [comment]
Just tested this with a old-old-old XP VM and the build that I did with Visual Studio 2017 doesn't seems to be compatible with the 17 years old operating system. Let me see if this is possible with my version of the compiler. This is a build issue and not a code issue.

**Comment by E-Gwen** [comment]
Thank you for your attention.
Yes, XP is an "old-old-old" operating system, but with Mixbus 4.3, Ardour 5.12, or Cadence 2.0.b6, it delivers a full up-to-date DAW. With Firefox 52.7.3ESR, it rules the internet !

Microsoft has no interest to support this 32 bits OS, and I'm not surprised that Visual Studio 2017 is not compatible with Windows XP.

I suggest you take a look to MinGW (http://mingw.org/), which is used to compile Ardour, and that makes this software fullly compatible with XP, if you have time enough, of course.
You could find method or example here : 
http://rawpedia.rawtherapee.com/Windows
https://docs.libretro.com/compilation/windows/

Thank you for your clear explanation.

E-Gwen.

**Comment by DESMSE** [comment]
Hi to all,


I've tryed to instal DEXED to XP SP3 framework 4.
I want use it with my TX7 and vst cubase sx.

Probem apair again "C:\Program Files\Dexed\Dexed.exe is not a Win32 valid application"

Could you please said me if there is a solved dexed.exe for this trouble?

Many thanks by advance,

Best regards !

Stephane (from Paris)

**Comment by E-Gwen** [comment]
Hi,

At this moment, the only way to use Dexed with Windows XP is to use the 0.9.3 version.

**Comment by DESMSE** [comment]
Hi Gwen,
wonderfull !!! Many thanks !

But where can I find thid vresion?

Many thans by advence,

best regards,

Stéphane

**Comment by DESMSE** [comment]
Hi Gwen,  found the 0.9.3 there :

https://github.com/asb2m10/dexed/releases

Lest go to try it !

Many thanks !
