### ISSUE TITLE
Parm Function Controls are not real time

### ISSUE THREAD

**Issue by rickyackel** [asb2m10/dexed#142]
Adjusting controls on the PARM panel only takes effect when you hit OK. 
1) Bring up Patch 7 on CARTF0/CART2B.SYX Which is SYN-CLAV 3.
2) On the PARM Page turn on EG BIAS for the Wheel and Change the Value to 99
3) Hit Low notes with PARM page up and adjust the Mod Wheel while listening
4) Hit OK to Dismiss PARM page and repeat step 3.

I think this is real time on the original DX7, but mine is acting up and won't play longer than half a second.

**Comment by asb2m10** [comment]
This is a work as design because it is a modal dialog. But can make it as non-modal so the parm function is real time.

**Comment by asb2m10** [comment]
This has been fixed since now any changes on the PARM dialog will be applied real time.
