### ISSUE TITLE
Please update Dexed build instructions

### ISSUE THREAD

**Issue by jayknowstheway** [asb2m10/dexed#143]
I think your work would be fantastic to try! However, the instructions are not clear. I'm left with a Dexed.so file that i have no idea what to do with. I've also tried to get the VST SDK which has been a nightmare to figure out. But maybe I don't need it? I'm not sure. Could you have a step-by-step list of things we need to do to get it up and running? Including possibly "obvious" steps (like.. if it needs to run in a DAW, say that?). Thanks!

**Comment by atrizdawiz** [comment]
I agree with this. Same situation here.

**Comment by asb2m10** [comment]
Dexed is now built with script helpers that is documented from the project README.md.
