### ISSUE TITLE
Keyboard problem

### ISSUE THREAD

**Issue by cagriaksoy** [asb2m10/dexed#147]
Hello I am very new in making music, I found this program but I can't use the keys bottom of my keyboard , I can only use qwert..... and asdfg...... keys. What should I do ?

**Comment by asb2m10** [comment]
Hi there. dexed actually relies on the DAW capabilities to do this; please take a look at those tools that will help you use the keyboard in what ever configuration, where dexed is simply a plugin.

https://reaper.fm/
https://www.renoise.com/
https://www.ableton.com/en/live/compare-editions/
