### ISSUE TITLE
Compatibility with Mac OS X 10.6.8

### ISSUE THREAD

**Issue by kgermain1** [asb2m10/dexed#148]
Hi! 
I was wondering if it would be possible to get a version that is compatible for mac OS X 10.6.8? I don't know if there is a high demand for that but it would be fantastic :)

Thanks!

**Comment by asb2m10** [comment]
Sorry, I'm not supporting OS X 10.6.8 since older SDK are difficult to support with recent macOS machines. Otherwise you can run an older version of dexed: http://le-son666.com/software/dexed/dexed-0.9.0-osx.zip

**Comment by pournaki** [comment]
Hi! Would it be possible to reupload 0.9.0 for OSX 10.6.8? I am in the same situation as @kgermain1 :) Thanks so much!
