### ISSUE TITLE
macOS Dexed standalone plays back with bizarre frozen flanger quality

### ISSUE THREAD

**Issue by PeterFrampgun** [asb2m10/dexed#151]
I'm on macOS 10.13.5 using Dexed 0.9.4. When I load Dexed in Logic Pro X, everything sounds great. When I load Dexed in Hosting AU <https://ju-x.com/hostingau.html> or use the standalone version, the same patches play back as if they're run through a flanger, and Dexed will "stick" a bit on one note, so that the whole played chord does not play back. It's really odd. I've experimented with different bit depth, rate, and buffer size settings, and I have not found a fix.

**Comment by asb2m10** [comment]
Can you make a video for this; this would help me understand the issue. 

Thanks.

**Comment by PeterFrampgun** [comment]
I've uploaded a zipped mp3 since I don't have tools that will record video and system audio together. First, you'll hear a C chord played by a sawtooth wave in Fabfilter One just to show you what I'll be doing in Dexed. Then you'll hear Dexed hosted in Hosting AU playing back with three different patches from the default bank:

1. Say Again.
4. PHAROH
8. OB GenvivY

It's almost like it's somehow holding down notes and not releasing them. 

Oddly enough, it works fine in Dexed standalone tonight. It's very strange as I have a number of other AUs and have never had this problem. The thing is, I only need to rely on it in Logic, and it works 100% fine there, and I suspect that won't change.

[Dexed-HostedAU.zip](https://github.com/asb2m10/dexed/files/2200024/Dexed-HostedAU.zip)

**Comment by asb2m10** [comment]
Weird... for me this there is two problems : 

1. Missing/hold notes :
- what version of dexed are you using (just click on the "DEXED" logo for the about box)
- do you have other midi devices connected on the same midi port that could generate extra message that corrupts dexed events ? Logic is probably filtering them...
2. Output sounds like in a flanger effect : 
- If you change buffer size (from very small to very big), does the "flanger" sound is different ?

**Comment by PeterFrampgun** [comment]
I'm sorry to be so late with this reply. I've tested again (Dexed 0.9.4), and the standalone version *works fine*. I think I made a mistake in saying that it didn't. [Hosting AU](http://ju-x.com/hostingau.html), which is sort of a mini-DAW on macOS, *does* have the flanging/sticking notes problem. Changing buffer sizes in the app did modify but not eliminate the weird behavior. I had these problems under High Sierra, and I'm on a current version of Mojave with the same problem. I'm using onboard sound.

Since Dexed standalone and the Dexed AU in Logic Pro X are working correctly, I'm willing to bet this is something odd happening with Hosting AU. I'll leave it up to you as to whether this is closed or should be further pursued. I'm okay with closing. Please let me know if there's anything else I can do, and I'll be more timely about it this time. 😄
