### ISSUE TITLE
"The complete dx7" link is broken

### ISSUE THREAD

**Issue by mikezaby** [asb2m10/dexed#160]
In [resources page](https://github.com/asb2m10/dexed/wiki/usefull-recources) "The complete dx7" link is broken

**Comment by pathworker** [comment]
Thanks for the heads up.
[The Complete DX7.pdf](https://github.com/asb2m10/dexed/files/2294897/The.Complete.DX7.pdf)

**Comment by mikezaby** [comment]
Thanks for share 👍

**Comment by asb2m10** [comment]
Thanks @pathworker for updating this.
