### ISSUE TITLE
FYI: Dexed selected for the Open Source Music FM Synthesizer Challenge

### ISSUE THREAD

**Issue by SpotlightKid** [asb2m10/dexed#161]
Hi there,

I hope it's ok to post this here, since I couldn't find any other contact info anywhere. Feel free to close this issue after reading.

I just wanted to let you know that Dexed is one of the FM software synthesizers we selected to be used for the Open Source Music FM Synthesizer Challenge, which we are organizing in September/October 2018:

https://fmchallenge.osamc.de/

Feel free to link to the competition on your homepage or tweet about it (you can mention @osamCologne) and if you would like to take part in the competition that would be very welcome indeed! :)

Best wishes and thanks for the great synth!

Christopher Arndt
Open Source Audio Meeting Cologne
http://osamc.de/
fmchallenge@osamc.de

**Comment by asb2m10** [comment]
Cool stuff, I'll leave this open until the competition is finished. (sorry, I'm not a tweeter user). You can contact me by using my github username with the gmail hostname.
