### ISSUE TITLE
Export txt file with 32 patches name

### ISSUE THREAD

**Issue by ballacr75** [asb2m10/dexed#162]
Hi, it will be wonderful if there is a button or context menu with "export to txt" that create a txt file with the same name of the loaded syx cartdrige containing the list of 32 patch name and all the parameter for each patch! Or make a new utility program that do that!
Thanks, Emanuele

**Comment by Sentinel77** [comment]
This utility does that.
https://github.com/rogerallen/dxsyx

**Comment by ballacr75** [comment]
Great, thanks so much, I'll check!
