### ISSUE TITLE
Transposed key 

### ISSUE THREAD

**Issue by kishmu** [asb2m10/dexed#169]
OS: Mac OS 10.14.2
Dexed version: v0.9.4hf1
Mainstage host or Standalone

The pitch sounded offset initially by the pitchbend range. So, if the key is F and the pitch bend range is 2, playing D# sounded F. As soon as I pull the pitch bend wheel and release it, the pitch is corrected (playing F on the keyboard sounds an F). 

This problem is not present in  v0.9.3.

**Comment by mkruselj** [comment]
I cannot confirm this issue with 0.9.6.

**Comment by kishmu** [comment]
It could be something on my side then. Thanks for looking.
