### ISSUE TITLE
Aftertouch not working under Win 10 64bit?

### ISSUE THREAD

**Issue by ipogeorge** [asb2m10/dexed#170]
Hi. New to Dexed here.
I'm testing dexed with a DX7 mk1. 
Aftertouch is not working on my stand alone Dexed. 
Aftertouch is perfectly working on my keyboard's sound generator. 
I see that the keys and the picth/mod-wheels do their work in Dexed, only aftertouch doesn't work.
Any idea? 
As a side note, the PARM page switches lack of any LED or any other mean to know if they are switched ON or OFF.  
You can memorize that pushing on the right side will be ON and on the left side will be OFF, but it's far from be immediate.
Kind regards.

**Comment by mkruselj** [comment]
@asb2m10 Aftertouch works just fine over here with latest Dexed. Can close issue 🙂
