### ISSUE TITLE
In standalone don't visible "dx7 in" parameter

### ISSUE THREAD

**Issue by fxsound** [asb2m10/dexed#171]
Good day!

In standalone (0.9.4HF1) don't visible "dx7 in" parameter.

![1](https://user-images.githubusercontent.com/38001850/52117252-52b85100-2624-11e9-84b5-c4421ba37583.jpg)

**Comment by asb2m10** [comment]
Hi,

This is normal since the DX7 In port is configured in the Audio/Midi when it is running in standalone.

The new version of JUCE now offers a way to select the midi out port from the Audio/Midi dialog and dexed will be able to use this dialog/port to avoid confusion.
