### ISSUE TITLE
Breath Control EG Bias not working

### ISSUE THREAD

**Issue by brianavid** [asb2m10/dexed#173]
Trying to use Dexed (0.9.4hf1) with a WX11 wind controller instead of my usual keyboard. Got the Patchman wind patches which need BC EG Bias to shape the notes. But I can get no perceptible effect with the breath control (CC 2). Is EG Bias supported?? 

I have confirmed with Midi-OX that BC (CC #2) is being sent correctly

**Comment by brianavid** [comment]
Further info: If I dynamically map CC 2 (Breath) to CC 1 (Wheel) and configure the PARAM settings to turn on Wheel EG BIAS instead, the sounds play fine. So the problem is with the specific controller and not EG BIAS as a whole.

**Comment by opus-quatre** [comment]
Hello Brian..
Did you solve the problem ?
In fact, it a matter of GUI.. On the parameter window, the labels have been inverted.. 
Where it's written "Breath ", in fact it corresponds to the foot pedal..
And where it's written "Foot", this is in fact the breath controller settings..
I suppose that some musician play upside-down.. Or maybe some walk on their breath controller to make it work..
Anyway.. This small issue should be easily mended.. I would do it if I had a single idea of how I can change that small, but confusing, and, with time, boring, inversion..
I hope it helps you..
And I wish someone could change the code line..
Have a nice week-end..

**Comment by brianavid** [comment]
Thank you so much for this. Swapping the settings is a very easy solution.
And it works perfectly. Much simpler than using Midi-Ox and loopMidi to
remap breath as mod wheel!

Annoyingly I had experimented to see if my foot controller worked. But it
didn't either - as I tried to use the "foot" param setting!!

I do like Dexed for wind control. The Arturia DX7 V emulation can't seem to
handle breath control at all other than by Volume CC

Thanks again

Brian

**Comment by opus-quatre** [comment]
I never tried Arturia DX7 V.. 
Nor did I read the manual..
But as they implanted Breath Controller inputs on their Keylab series (Keylab 25, 49, 61, 88, 1st generation).. But also on The Laboratory 49 and 91.. Then I would expect them to have implemented it on their DX too..
Anyway, people at Arturia are very nice people.. You should eventually contact them and ask ?
And did you try the "MIDI Learn" technique ?.. Sure it's different, but it might help..
See you..
Thierry

**Comment by opus-quatre** [comment]
I just downloaded the DX7 V manual..
on the French manual, page 94+, I see that, by using the modulation matrix, you can set Breath Controller as source, and so many parameters as destination.. Much more complete than on the DX7 or on Dexed..

**Comment by brianavid** [comment]
Thanks again for this.

I had experimented with DX7 V modulation destinations, but with little
success.  But as you say the guys at Aruria are friendly, I have mailed
them a "How to" support question:

**Comment by brianavid** [comment]
Thanks again for this.

I had already experimented with DX7 V modulation destinations, but with
little success.  But as you say the guys at Aruria are friendly, I have
mailed them a "How to" support question:

I have an old (still working) Yamaha wind controller, and the DX7 wind
patches from Patchman, which make extensive use of the "EG Bias" to shape
individual notes. I can play this effectively with Dexed by using its
implementation of EG Bias.

But I can't find any way of configuring a modulation destination in DX7 V
to achieve the same sound. It is certainly not the same as modulating
volume. And I could possibly modulate each of the OP levels (or maybe only
the carrier OP levels?) - but that seems very messy.
Is there a suitable modulation destination that I have missed that
recreates the original DX7 "EG Bias"? Or should I stick to Dexed for wind
playing?


Regards

Brian

**Comment by opus-quatre** [comment]
On the original DX7, and on Dexed, you set the amount/depth of breath modulation as a global parameter (Breath 0>>>99, pitch  0/1, amplitude 0/1, EG bias 0/1)..
And that's global, for all presets..

And inside each preset, each operator will be influenced by the Breath Controller, depending on the "a mod sens" parameter, which is personal/independant for each operator..
If you want to modulate amplitude/volume, of the sound, then you raise up the carrier's "a mod sens"..
If you want to modulate the harmonic content, the brightness of the sound, then you raise up the modulators "a mod sens".. from 1 to 3, depending on the depth of modulation that you want to apply on each modulator..

 Those parameters also are on Arturia DX 7V.. They are called "AM Sensitivity" What I can't find is the global parameter..

What I have seen on the Arturia DX 7 V manual is, that you can select (in the mod matrix) Breath Controller as source, and as a possible destination; I can see "Volume", but also "Modulators Level".. The first one will set the influence of the BC to the overall volume of your sound, while the second will set the influence of BC to the brightness/harmonic content of your sound..
This is not an inidividual operator setting, it concerns ALL the modulators.. But it's a quick setting which would give you some results..

I can also see, as possible destinations,  op1, op2, op3, op4.. And below, linked with a small line, I can see "pitch", "level", "envelope".. I suppose that you select an operator, and then you select "level", and you set it.. But you can also select "cutoff", or "pitch".. This sounds terribly more powerful than the original DX7 method..

I would open one of the preset in Dexed.. I would not down, for each operator, the "A mod sens" value, and then I would open the same preset in Arturia DX7 V, and I would report those values in the Mod Matrix, operator per operator, multiplied by a (unknown) coefficient.. I would be intuitive to find the coeff..
That is.. If I had DX7 V !! eh eh !!

**Comment by brianavid** [comment]
Thanks for this. It certainly gives me plenty to play with. I had
previously experimented with modulating operator levels with breath, but
the effect was not the same. Maybe I was not patient enough!

I will wait to see if I get a reply from Arturia about EG Bias. I have read
DX7 V described as a powerful modern FM synthesizer that maintains support
for original DX7 SysEx format voices. This is true for the ROM voices (if
you change the velocity range from the system-wide default), but I
understand that breath control is a niche requirement and could easily have
been forgotten when designing the backward compatibility.

And of course, as long as I only want to use original DX7 voices, and not
benefit from any Arturia additions, I still have the option to use Dexed
for that instrument.

**Comment by mkruselj** [comment]
EG BIAS is just multiplying operator's envelope amount with the modulator's value times a factor set with RANGE. On Arturia's DX7 V you simply do this by directly modulating operator volume with whatever modulator you want, it's exactly the same effect really.

**Comment by mkruselj** [comment]
@asb2m10 This issue can be closed, I think. The issue was with labels on PARM page being swapped, this was resolved IIRC.
