### ISSUE TITLE
Program names are not available until editor is opened

### ISSUE THREAD

**Issue by Drachenkaetzchen** [asb2m10/dexed#175]
Hi,

it seems that the program names aren't loaded until the plugin editor is opened. I noticed this problem when attempting to reproduce a bug in [PresetMagician](https://presetmagician.com/) and noticed that all program names were empty.

I then used [mrswatson](https://github.com/teragonaudio/MrsWatson/) to ensure it's not a problem with my VST host implementation, and it seems it's not. Outpout of mrswatson (stripped to show only the program names):

```
- 00000000 000969 Programs (32 total):
- 00000000 000985   0: ''
- 00000000 000985   1: ''
- 00000000 000985   2: ''
- 00000000 001000   3: ''
- 00000000 001000   4: ''
- 00000000 001000   5: ''
- 00000000 001000   6: ''
- 00000000 001016   7: ''
- 00000000 001016   8: ''
- 00000000 001016   9: ''
- 00000000 001016   10: ''
- 00000000 001016   11: ''
- 00000000 001031   12: ''
- 00000000 001031   13: ''
- 00000000 001031   14: ''
- 00000000 001047   15: ''
- 00000000 001047   16: ''
- 00000000 001063   17: ''
- 00000000 001063   18: ''
- 00000000 001063   19: ''
- 00000000 001063   20: ''
- 00000000 001063   21: ''
- 00000000 001078   22: ''
- 00000000 001078   23: ''
- 00000000 001078   24: ''
- 00000000 001078   25: ''
- 00000000 001094   26: ''
- 00000000 001094   27: ''
- 00000000 001094   28: ''
- 00000000 001094   29: ''
- 00000000 001110   30: ''
- 00000000 001110   31: ''
- 00000000 001110 Current program: ''
```

Being not familar with Juce and it's calling sequences, I would assume that [createPluginFilter](https://github.com/asb2m10/dexed/blob/73a266dd70e58e7def14a52bf2a53b5486d083dc/Source/PluginProcessor.cpp#L290) would be called during loading of the plugin, so it's puzzling why the program names are not initialized - however, my assumption could be wrong.

I might try to build a debug version which includes logging at a later point it time, but that's all I can report for now.

**Comment by Spacechild1** [comment]
I noticed the same behavior in my VST host.
