### ISSUE TITLE
Patch loads from cart don't persist between song stop/starts

### ISSUE THREAD

**Issue by skyshock21** [asb2m10/dexed#178]
In Logic 10.3.2 on OS X Mojave, no matter what patch I load from a .syx cart, the preset reverts back to "Factory Preset 31 'Take Off'" whenever I stop/start the track.  How can I get the cart setting to save and persist between song stop/starts?

**Comment by dronus** [comment]
Most likely the track contains a "Program Change" command and requests Dexed to switch to Patch 31.  So you need to change your track / patch settings in your MIDI workstation.

**Comment by skyshock21** [comment]
Sufficient time has passed between initial report and response that the issue is no longer relevant. Closing.
