### ISSUE TITLE
Dexed crashes when changing ALSA MIDI inputs

### ISSUE THREAD

**Issue by Mittagskogel** [asb2m10/dexed#179]
I usually use the Dexed standalone on manjaro linux (xfce). Using it as a plugin with Ardour seems to be utterly impossible as it will crash randomly when used with other plugins. In that case I don't even know whether the fault lies with Ardour or Dexed.
To get to the main point, the Dexed standalone crashes when I enable or disable MIDI channels in the options menu. In my case, I have set up 16 ALSA MIDI through ports. I use several instances of Dexed for different instrument parts so each instance needs to receive on a different MIDI through port. However, when enabling and disabling ports, Dexed frequently crashes, or simply ignores the settings and listens on ports it shouldn't be listening on while ignoring the relevant ones.

Sorry for sounding a bit annoyed, but the constant crashes are super frustrating if they continue to get in the way when trying to make music.

**Comment by asb2m10** [comment]
Did you try to build it with the latest version of JUCE ? I know that the API did had this issue when Dexed was packaged.

**Comment by asb2m10** [comment]
I will close this issue since I didn't have any update.
