### ISSUE TITLE
Can't send / receive Sysex on Ardour

### ISSUE THREAD

**Issue by dronus** [asb2m10/dexed#180]
If Dexed is used as Ardour plugin, it does not send patch data to the MIDI interface, nor does it receive incoming Sysex from MIDI devices. The Ardour track and plugin is correctly configured to use the hardware MIDI interface. 

Is this by design, a bug, or Ardours flaw?

**Comment by asb2m10** [comment]
I'm not an Ardour user but I know that in Live any Sysex data passing trough the midi stream is actually removed by the host. It is the reason why you can configure another midi device in the PARM window, it is to send and receive sysex. 

That was in 2014 with VST2, maybe in VST3 this is possible but I don't know if it is the spec or the host that strips the Sysex. If the host sends sysex data, Dexed should be able to parse it correctly.

**Comment by jpcima** [comment]
It can be expected that system-exclusive events will not work in ardour, with the VST2.
Ardour, and also LMMS and others, are designed around a royalty-free, reverse-engineered version of St*****rg SDK known as vestige, which has reduced abilities.
One ability which vestige lacks is system-exclusive messages, unfortunately, so these messages will not be recognized at host level.
A LV2 plugin would not have this limitation.

**Comment by dronus** [comment]
Well, if any MIDI data is just transmitted as-is through the DAW, SysEx would be no problem..... nothing the plugin host has to do about. Why are VSTn intefaces tampering with the MIDI data?

**Comment by jpcima** [comment]
Unfortunately, the MIDI message queue of VST has a different encoding the short messages (size 1-4), and the system-exclusive ones. Vestige has only support of the first kind.

**Comment by asb2m10** [comment]
I'm closing this since it is already documented in the wiki: https://github.com/asb2m10/dexed/wiki/Dexed-as-a-DX7-editor

If you see better wording for this, you are welcome to change this.
