### ISSUE TITLE
UI upgrade status

### ISSUE THREAD

**Issue by FrancescoBia** [asb2m10/dexed#182]
Hi @asb2m10, is there any update regarding the UI redesign?
I love the effort that has been put to put together dexed, and would like to offer my help –if needed– for the UI upgrade, being an interaction designer. I often felt there could be a couple of improvements that would definitely improve the UX and general usability of the plugin, and I would be interested to understand your vision for the UI redesign! Let me know if I can support somehow or even just give an external opinion.

**Comment by asb2m10** [comment]
Hi Francesco, yes an UI update would be welcome, but I need to confirm that I can assert time to support all this in a timely matter. I'll contact you by email soon.
