### ISSUE TITLE
GUI breaks audio in Ardour with realtime priority

### ISSUE THREAD

**Issue by dronus** [asb2m10/dexed#186]
If Ardours audio engine is allowed to run with realtime priority, opening the Dexed GUI causes a massive wave of buffer underruns. This state even prevail after closing the GUI again, and requires an Ardour restart to recover.

Drastically increased ALSA buffers (eg. 44ms instead of 11ms)  mitgate this problem, but this renderes realtime scheduling useless and leads to unacceptable latency.

Revoking the realtime priority remedies this problem (but requires 22ms latency on my system for reliable audio). 

My guess is that some GUI related operations accidentally take place in Dexed's audio processing loop that would be called by Ardours realtime DSP thread.  Can anybody confirm this?

**Comment by dronus** [comment]
Just did a cross check with other plugins UI's: Neither heavy custom UI plugins (like from the Calf pack) nor Ardour generated UIs for UI-less plugins exhibit this problem. 
Also using an Ardour generated UI for Dexed does not trigger this problem.

**Comment by asb2m10** [comment]
Dexed is design to pull for DSP context from the UI thread (E.G. the DSP never handles UI stuff). I didn't saw any issues with other DAWs.

That said, older Dexed version did stress the UI redraw stuff and the new version is way more optimized:

https://github.com/asb2m10/dexed/releases/tag/v0.9.7pre4
