### ISSUE TITLE
Inversion Breath/Foot on "parameters" window..

### ISSUE THREAD

**Issue by opus-quatre** [asb2m10/dexed#188]
Hello there..
Just wanted ask for a slight modif..
On the parameter window, "Foot" and "Breath" labels have been inverted.. Would anyone change the line code for the labels to be at their proper place ?
If I were able to do it, I would.. But in terms of programming, I'm totally disabled..
Have a nice day..
Thierry

**Comment by trebmuh** [comment]
[originated from here](https://github.com/asb2m10/dexed/issues/173#issuecomment-520007802)

**Comment by opus-quatre** [comment]
Do you ean I should delete y issue..
By the way, bonjour Olivier..
But I' afraid that the "here" is a conversation about using Breath
Controller, and I' afraid that no one will read it and will understand that
there is soe issue in the param window, which needs to be soved..


Le sam. 10 août 2019 à 11:49, Olivier Humbert <notifications@github.com> a
écrit :

**Comment by trebmuh** [comment]
No problem here, I was just giving a bit of context in my previous message.
