### ISSUE TITLE
Cannot compile on Windows.

### ISSUE THREAD

**Issue by kroaton** [asb2m10/dexed#191]
Hi,
I want to mess around with modding Dexed (more waveforms etc.) and as such I'm trying to build on Windows, using Visual Studio 2017. I've tried to get it to compile for the last 6 hours or so but keep running into these errors: 
![Screenshot_20](https://user-images.githubusercontent.com/6411688/66272891-b829a500-e877-11e9-9325-5f1bb3c31b5a.jpg)

**Comment by asb2m10** [comment]
I've just pulled that lasted dexed git and I don't have these errors with VS 2017... did you upgraded the JUCE framework ? dexed needs adjustment to be able to compile with the latest version of JUCE.

**Comment by kroaton** [comment]
Yes, I upgraded to the latest version of JUCE. What version are you running? Also, thank you for the quick reply!

**Comment by kroaton** [comment]
I managed to compile it. Before, I was trying to do it through the ProJucer (never used JUCE before) while all that had to be done was to load the build files from dexed_master into VS2017, set the target to x64 and compile Dexed_VST.

Thank you very much!
