### ISSUE TITLE
Building on Debian Buster

### ISSUE THREAD

**Issue by tank-trax** [asb2m10/dexed#195]
ran into a snag

`error: ‘nonexistent’ is not a member of ‘juce::File’`

used the modules in `dexed/JuceLibraryCode`

un-commented line 207 of `dexed/JuceLibraryCode/AppConfig.h`

`#define JUCE_ALLOW_STATIC_NULL_VARIABLES 1`

and build proceeded successfully

although there were multiple warnings

`warning: "TRACE" redefined`

**Comment by asb2m10** [comment]
Just pull the latest source since I've migrated to JUCE 5.4; it should compile out of the box (with a lot of warnings that I'm cleaning right now).

**Comment by tank-trax** [comment]
it doesn't build the VST2 any more

**Comment by asb2m10** [comment]
VST2 has been removed from JUCE per Steingberg requirements. You will need the VST2 SDK if you want that target.

I will still provide VST2 binaries for future releases but the open source config will remain on VST3. Sorry but Steinberg wants us to really move on VST3 :face_with_thermometer:

**Comment by tank-trax** [comment]
@asb2m10 I have the VST2 SDK, I selected VST2 in Projucer and it still only builds the Standalone. Is there something missing?

**Comment by tank-trax** [comment]
I managed to build the VST2 by dragging over a previous Makefile I fortunately had backed up. Has something changed in the code that is not adding the directive to build the VST to the Makefile via Projucer?
