### ISSUE TITLE
Some users are confused because virus total said it could be a virus.

### ISSUE THREAD

**Issue by Ollo123** [asb2m10/dexed#197]
Some users are confused because virus total said it could be a virus.

**Comment by mkruselj** [comment]
It's a false positive. Report to virustotal that their heuristics are going wild and that Dexed is a valid binary.

**Comment by asb2m10** [comment]
[Hybrid Analysis](https://www.hybrid-analysis.com) shows that 3 virus vendors confirms that Dexed **from github** is clean.

https://www.hybrid-analysis.com/sample/14584efcc190be8dab4fc72ddc9f6f88c560ffb069288fd90e82e6a20e206094
