### ISSUE TITLE
What happened to the Linux VST2 build?

### ISSUE THREAD

**Issue by SpotlightKid** [asb2m10/dexed#198]
Currently, when compiling from the latest git on Linux, only the standalone version is built. No `Dexed.so` VST library can be found in `Build/Linux/build`.

**Comment by tank-trax** [comment]
On Debian Buster 10.2

I noticed this too, I had kept an older Makefile which allowed me to build the VST2.

**Comment by asb2m10** [comment]
Sorry, but I had to upgrade JUCE that didn't include VST2 anymore, for [Steinberg licensing reason](https://forum.juce.com/t/the-future-of-vst2-support-in-juce/28077). 

I'll have to look if I can provide a dynamic building approach where if there is a VST2 sdk, it can use this path, otherwise just build VST3 that is bundled with JUCE.

I keep it that way so open source Dexed can be build without any esoteric steps that are needed to get the VST2 sdk.

**Comment by tank-trax** [comment]
unfortunately VST3 plugins can't built using JUCE on Linux yet, and ROLI has kept their cards close to the chest on this one, they've said it's a priority for them but it's apparently presenting them with a formidable challenge

This [comment](https://forum.juce.com/t/vst3-support-on-linux/31872/3) from Feb 2019

>Yep, we’re currently investigating and it’s a considerable amount of work. The Linux VST3 SDK requires that hosts expose an event loop to the plug-in so it can register file descriptor and timer event handlers and getting this to work nicely with JUCE’s existing event loop basically requires a complete re-write of the Linux messaging code. On the client side, we then need to hook into the host’s event loop which again is non-trivial.

> It’s a high priority for us, but unfortunately giving exact timelines isn’t something that we can do right now.

**Comment by asb2m10** [comment]
That is ridiculous.... The fact that they have to re-write the event loop just for an API support is beyond my understanding. I remember u-he and Ableton having a hard time adapting their code for VST3... It is so sad that it became the standard multi platform plugin format.

Ok, I'll re-enable VST2 but the old sdk will have to provided upon builds, just like the old days. Because of this I'll have to disable the automated build.

**Comment by alecvn** [comment]
Sorry to hijack this issue but I'm just wondering how to build Dexed on Linux.  According to [this](https://github.com/asb2m10/dexed/wiki/Linux-Builds) there's supposed to be a `.so` file but I only see a binary and a `.a` file and neither seem to be picked up by Reaper as a VST.

**Comment by tank-trax** [comment]
@alecvn 

for some reason it's not linking the VST, did it build the standalone? do you have the correct VST2_SDK?

you can try this [fork](https://github.com/surge-synthesizer/dexed) 

there are some scripts that could help

**Comment by alecvn** [comment]
Don't think I have a VST2_SDK at all, wasn't aware it's a requirement.  Is there a section that details requirements and install processes?

I'll look into the fork, thanks.

**Comment by alecvn** [comment]
Sorry - it did build the standalone, but I would like to use it as VST in Reaper and would prefer not having to load it via Carla or similar if I don't have to.

**Comment by tank-trax** [comment]
@alecvn if you didn't download the VST2_SDK back before 2018 there's no way to build the VST2 as Steinberg no longer distributes it and has put out take down orders to have them removed from the Internet. Sorry.

Hopefully ROLI figures out the VST3 runtime issue and we can move on from VST2, but I am not holding my breath

it would be nice if ROLI invested some time in making a credible LV2 alternative for JUCE

**Comment by trebmuh** [comment]
> it would be nice if ROLI invested some time in making a credible LV2 alternative for JUCE

They doesn't look to take this way: https://github.com/WeAreROLI/JUCE/issues/123

**Comment by alecvn** [comment]
So my only option is Dexed standalone via Carla Rack to Reaper?

**Comment by SpotlightKid** [comment]
You can also try the DISTRHO LV2 port of dexed (also wrapped with Carla):

https://distrho.sourceforge.io/ports.php
https://github.com/DISTRHO/DISTRHO-Ports

It may not be fully up to date with the latest changes in this repo, but it generally works.

**Comment by baconpaul** [comment]
With the merge @asb2m10 just did (thanks!) if you have a VST2SDK the new build scripts can configure projucer for you and build a vst2. Check the bottom of the README

With some of our other synths, we have had good luck with juce6 making linux VST3s also. I hope to also do a dexed juce6 port later in the week and try dexed in Linux REAPER VST3 also then.
