### ISSUE TITLE
Illegal Instruction Debian Buster Dexed 0.9.4

### ISSUE THREAD

**Issue by tank-trax** [asb2m10/dexed#199]
On Buster Debian 10.2

I recently tried [dexed-0.9.4.lnx.zip](https://github.com/asb2m10/dexed/releases/download/v0.9.4hf1/dexed-0.9.4.lnx.zip) and the Standalone crashes with an Illegal Instruction and the VST crashes all DAW's

I am able to build the VST2 (must hack the Makefile) and Standalone locally which both work

**Comment by asb2m10** [comment]
That's probably the ALSA Midi/JUCE issue upon listing devices. See #184 

If you have built the latest version from my repo, you should not see this issue, please confirm so I can double check.

Thanks.

**Comment by tank-trax** [comment]
I have built Dexed locally (I am also involved with Surge Synth) and it works perfectly. It's the prebuilt binary on the Releases page that gives the Illegal Instruction.
