### ISSUE TITLE
How would you like to handle dexed changes?

### ISSUE THREAD

**Issue by baconpaul** [asb2m10/dexed#205]
Hi!

First, thanks for all your work on dexed. It is such a great sounding synth!

Over in the fork I mentioned in #201 I now have  complete SCL/KBM implementation working which matches pianotec and surge on all the scales we've tried. One item left to finish and make it a PR (which is to have an option to show the current tuning). Along the way I also upgraded some of the deprecation warnings, made the modal param dialog a bit better, and a few other things. I also relabeled the labels in #200 in the projucer file as opposed to the generated code. A bit of work to do before I package it as a PR against master but not much.

And that sort of has several of us over in surge land thinking: if we want to make a few larger changes to dexed (CI Infra, SCL/KBM, some UI improvements, and some MPE support are our rough list) would you rather we push them over to you as PRs (which means new builds and so on especially if you have a different CI infrastructure) or should we do a fork?

I am sort of reticent to do a fork, not for any legal reason (it's all GPL3 or Apache 2) but sort of for a social reason - to fork your product and add a bunch of features and not talk to you is just rude! But I'm also sort of reticent to be that guy who shows up with a bunch of PRs when you have this project running at a fairly low activity level on a stable beloved product. Speaking as an OSS owner, I can see both as being annoying!

Also some of our changes - like KBM/SCL support and MPE support - will mean dexed has features "bigger" than a DX7. You say in your readme if you add features "bigger" than a DX7 that should be a fork.

But open source works well when we all chat. You've made a wonderful bit of software. Over in surge team land we have some ideas for some concrete additions, and we have capacity to do them. Any thoughts on how you would like that to evolve?

And thanks again for all your work on dexed. It's great!

**Comment by baconpaul** [comment]
Hello!

So I got all of KBM/SCL working and so we have decided to maintain a fork over at surge-synthesizer/dexed along with the other FOSS synths the surge team is working on.

*I would be thrilled to merge our changes back with you at any time* but also understand how taxing being an open source maintainer is, and understand you being happy for us to just go on our way.  So let me close this issue and the azure issue too, and if you decide you want to start spending some time looking at our fork please either reopen them or hit me up on github.

And thanks again for a great synth!

**Comment by asb2m10** [comment]
Hi, 

Sorry for the late reply, I was about to reply but had to think this thoroughly...

I've kept JUCE generated code within dexed cause some fixes were required to fix small bugs. Like the Linux midi naming device that caused a SEGFAULT. Other stuff in 2014 that I can't remember... It gets fixed by the official JUCE repo afterwards. But it is there to be able to do a full working release with dependencies. Maybe it is not required anymore but I found it useful not to push ROLI for my fixes.

While not perfect, Linux users can simply run make and it builds the complete solution. I think this is important. Your pull request was breaking this requirement. On your side (Azure Pipeline) you can simply delete the JUCELibraryCode directory and do what you want afterwards. Can we keep both build system ? 

Dexed changes related to KBM/SCL and MPE are certainly welcome. When I said anything beyond the DX7 should be a fork, it was more about DX7 architecture. If I remember right the DX7 II supported microscaling; we should follow the same path. What do you think ?

I'm happy to see new blood into dexed, believe me, this is my primary reason to work on it.

**Comment by baconpaul** [comment]
Oh cool! I added Linux to our branch this week so you can just run a pair of scripts and Linux builds (I haven’t written this in a readme yet but the activity if you clone surge-synthesizer/dexed is

- scripts/get-juce.sh
- scripts/projuce-Lin.sh
- scripts/build-Lin.sh

And you get the standalone. I was going to add an option to projuce that if you have an env set pointing to the vst2sdk it builds that too but obviously bring your own. Lemme write up that build direction stuff in our fork today

I did tuning by drag n drop of scl and kbm files. We had a convo in our slack (tagging @jackyligon) about what internal structures the dx7 used and would move to adapt to those too

Finally last night I got mpe pitch bend support running and was able to play dexed with my linnstrument. I plan to merge that today.

Right now I’m running quite a bit ahead of your master with a binary build available - and we have made some ui tweaks too (some improved contrast, some mouse wheel support, and also making the param window not os modal) but maybe in the weekend I could share a longer list of what we have together?

And like I said: in an ideal world we wouldn’t fork! Very happy to see your response

**Comment by mkruselj** [comment]
>If I remember right the DX7 II supported microscaling; we should follow the same path. What do you think ?

It did, but with limited resolution of 1024 cents per octave. Scala format (and @baconpaul's implementation) offers much greater precision.

**Comment by baconpaul** [comment]
Oh just an update: I pushed some changes today including documentation, which let you build no problem with a small set of scripts that download everything you need and run jucer in real time

I also added MPE support - at least the voice management and pitch bend handling.

So chugging along down a feature list. It's all up at https://github.com/surge-synthesizer/dexed.git including downloadable binaries now for all platforms!

**Comment by baconpaul** [comment]
Oh and I added a simple one or two line command for linux users where, if they have a valid copy of the VST2SDK, they can build the VST2 themselves, even though we and our pipeline only build the standalone for reasons I know you know etc...

**Comment by asb2m10** [comment]
I've tested the build on my side, works out of the box. :+1: Don't hesitate if you want to merge, they are certainly welcomed.

**Comment by baconpaul** [comment]
Cool! Let me do one or two other tweaks and I will get a big PR together this week. Super excited to get this merged!

**Comment by baconpaul** [comment]
The big tweak I want to do is that we have factored our tuning library into a standalone lib so multiple synths can use it without copying. I want Dexed to use that before I send you a PR.

Oh also: If you want help setting up the azure pipelines so there is a binary over here, it's really easy! I'll write that all down when I get the PR together this week.

**Comment by JackyLigon** [comment]
Thanks @asb2m10. It's been very exciting to work with Dexed since the implementation of the complete Scala SCL-KBM microtuning format, and has been a kind of a dream-come-true, having worked with Yamaha's FM synth line in microtonal music since the 1980s. We all really appreciate your work on this excellent virtual-instrument. Warm regards.

**Comment by asb2m10** [comment]
Any news on when the PR will be ready ? I'm ready to add some features but I would like to merge it first.

**Comment by baconpaul** [comment]
Oh I'm so sorry.... we found a couple of bugs in the MPE handling and then I had to leave my studio where all my MPE devices were. Let me try and get it together this week.

But don't hold up on my account. I can rebase to you also.

**Comment by baconpaul** [comment]
oh and I've been playing with juce6 some this week. It will make life soooo much easier for dexed and other open source products as far as releases and builds go. I pushed another one of our synths to it already in beta!

**Comment by baconpaul** [comment]
Just looked. It is only one bug we have left. https://github.com/surge-synthesizer/dexed/issues/50

I'll put it top of my stack and, all going well, should have a big PR for you in a day or two

Sorry for the delay.
