### ISSUE TITLE
Mono button not mappable in Ableton 'configure' option

### ISSUE THREAD

**Issue by janwillems5** [asb2m10/dexed#207]
Hi All,

When using the Ableton 'configure' setup for the Dexed device i find that i can midi map all parameters, but not the mono button? It would be great when playing live to be able to go monophonic without using the mouse!
Is this possible?
Thanks!

**Comment by asb2m10** [comment]
The mono/poly parm is part of the "function" parameters that are not exposed as VST parameter since it is not stored in the sysex. 

This is definitely an enhancement that should be addressed.

**Comment by janwillems5** [comment]
Hi, thanks for the fast answer! So should i post it somewhere in a future request section or something? Or is this something i can do myself?
