### ISSUE TITLE
Why disable OSS VST builds?

### ISSUE THREAD

**Issue by plaimbock** [asb2m10/dexed#209]
Hi, thanks for dexed! Can you please share why you disabled the OSS VST plugin builds in commit 2b9a6a238d28fc55f1a863acb047343ac3a6aa36
The dexed VST2 plugin works fine in Bitwig on Linux.

**Comment by asb2m10** [comment]
JUCE had to remove the VST2 SDK into original source which broke the automated build. Right now, JUCE on Linux doesn't support VST3. For now, use the release that still has the VST2 included.

The build system will have to be rework to be able to build a complete OSS version without VST support and another one if you provide the VST2 SDK.
