### ISSUE TITLE
Create sysex file from DX7/TX7 Cartridge

### ISSUE THREAD

**Issue by jolefrei** [asb2m10/dexed#211]
Hello everyone, 
I'm not sure I'm at the right place but I couldn't find an answer to my problem anywhere.
I own a DX7 and a TX7.
I'm using Dexed 0.9.4 on a Mac. Works great to send cartridges to my DX7 but before I do the same with my TX7, I'd like to save the patches that are already loaded inside.
Is there a way to transfer a cartridge from the TX7 to Dexed (or another software?) and create a sysex file with currently loaded patches ?
Thank you !

**Comment by asb2m10** [comment]
I don't own a TX7 so I cannot comment on this since it doesn't have the same interface as a DX7. You could ask the question on Reddit in the /r/synthesizers sub.
