### ISSUE TITLE
Jack and ALSA issues (solution found, but a pain)

### ISSUE THREAD

**Issue by revereche** [asb2m10/dexed#217]
I got the first two install scripts for Linux working off the bat, but running on Linux Mint, the last script gave me trouble. It was looking for alsa/asoundlib.h and jack/jack.h to build a script in juce_audio_devices. I got it working by downloading libasound2-dev and libjack-jackd2-dev, respectively, though I don't know what non-Ubuntu/Debian equivalents would be. Might be good to make a note of this, at least.

Awesome program to have working now, thanks for putting it together!!!

**Comment by trebmuh** [comment]
It is already written [in the wiki](https://github.com/asb2m10/dexed/wiki/Linux-Builds).

**Comment by revereche** [comment]
All right then, I didn't see it mentioned in the readme, which seemed to imply that the shell scripts took care of all dependencies for you.
