### ISSUE TITLE
 Dexed seems not handle single patch sysex data 

### ISSUE THREAD

**Issue by Totor42** [asb2m10/dexed#219]
With my DX7II in single mode (DX7 sandard) :
I upload current patch temp sysex data  (bulk dump) with MidiOX. Save it as sysex then trying to load it with Dexed and  get error message (corrupted sysex) !
I've checked format and ok it conforms to specification (sysex txt file)
A: SYSEX Message: Bulk Data for 1 Voice
F0
43
00
00   format number (f=0; 1 voice) 
01   byte count MS byte
1B   byte count LS byte (b=155; 1 voice)
xx   data byte 1
xx   data byte 155
cs   checksum (masked 2's complement of sum of 155 bytes)
F7 

Fred

**Comment by SamuelSHrk** [comment]
As far as I know, Dexed only supports Mark 1 DX7 patches

**Comment by Totor42** [comment]
Ok but when DX7II is in Single Voice", it behaves like DX7MKI. I f you look at sysex format in both manuals , it 's EXACTLY the same format which is used for temp data dump  :  1 voice bulk data :
F0 43 00 **00** **01 1B** ... 155 bytes ... **CS** F7 !

**Comment by encore64** [comment]
I think Dexed currently doesn't handle Single Voice Dump, only Bulk Dump Packed Format (with 32 voices). The latter is a more densely packed format.

Some more info in: https://github.com/asb2m10/dexed/blob/master/Documentation/sysex-format.txt

**Comment by Nintorac** [comment]
I have no problems applying single voice updates following the single voice dump spec in @encore64's link

the following file is a midi containing a single voice update that works for me. just rename to `.mid` (github doesn't allow midi in comments)

https://user-images.githubusercontent.com/24326299/81236572-d55a6800-9040-11ea-9f83-461cbcd37a2d.jpg

**Comment by Totor42** [comment]
Thanks for .mid file. Trying to load with dexed ... corrupted ! Doesn't works  ! Rename it to .syx... idem !
Let's look inside hex data : F0 43 00 00 **20 00** ... ... CS F7 ! Wrong format ! However there are sure 155 bytes **01 1B** inside this .mid file. The format 00 isn't correct and the size of **20 00** (4096) should be correspond to a bulk dump of 32 voices with format 09. So Dexed doesn't support yet single patchs !

**Comment by Nintorac** [comment]
Oh, thanks for picking that up. Making the fix in the code it still works to load the patch.

I have noticed that if you load it through the UI it doesn't seem to work though. I have been sending these messages to the midi input of Dexed

**Comment by asb2m10** [comment]
Loading single programs from the UI is not supported since the baseline of file management is based on 32 program dump (cartridge). This is to keep the UI consistent.

Otherwise you can stream single programs from the midi stream.

If you want to bundle single program into a full cartridge, I would suggest this tool: http://dxconvert.martintarenskeen.nl/

**Comment by Totor42** [comment]
>  the baseline of file management is based on 32 program dump (cartridge). This is to keep the UI consistent.
Yes, that 's what i understand for Dexed but for from the point of basic features of an an editor, if you are a patch programmer , single patch design and edit from scratch is the basic feature of an editor and in this way i don't undertsand why i have to embed 31 others patchs  from nowhere. 
On the web, there are a lot of sysex files with 32 voices bulk dump format. If you load it with dexed, only the first patch location is visible and all other are init patchs with no names (blank). Ok you can edit it as a single patch bank but will be save again with 32 voice format .

**Comment by asb2m10** [comment]
Sorry, Dexed wont support single program since it complexifes the way it can store data. A user could easily save a single voice into a single 32 voice cartridge. Lets keep this simple. Like a DX7, it only can save/restore a cartridge.
