### ISSUE TITLE
Anyone tried compiling dexed for AudioUnits?

### ISSUE THREAD

**Issue by BeFiveINFO** [asb2m10/dexed#22]
I tried compiling dexed (AudioUnits only) for 64bit binary with XCode 6.1 running on Yosemite.

I modified the following lines in JuceLibraryCode/AppConfig.h to
#define JucePlugin_Build_VST              0
#define JucePlugin_Build_AU               1

But I get Parse Issue Unknown type name 'Point' in Finder.h as well as in Quickdraw.h.
I also tried with the latest juce library (I also had to install AudioUnits header) and I could go only up to where I got loads of "Undefined symbols for architecture x86_64". 

Is there anyone that got the same problem?

**Comment by asb2m10** [comment]
Thanks devil-tamachan for the fix, I will add this to the 0.8.1 branch. As soon as the parameter refactoring is done and AU validation tool passes I'll update this issue so people can test it.

**Comment by asb2m10** [comment]
AU support is now committed in the 0.8.1 branch. Everything should be fixed for AU stuff (the au validation tool pass).

**Comment by BeFiveINFO** [comment]
Thank you very much!

Build was successful but it got errors and is without any sound output. Here is the validation tool output gist:

DEXED Validation error output from Logic PRo X (AU Validation Tool) Source - work-0.8.1 0d38241
https://gist.github.com/BeFiveINFO/128787fd83abf198c144

**Comment by asb2m10** [comment]
Hmmm, can you test my build to see if you have the same errors? 

http://le-son666.com/software/dexed/dexed-0.8.1-au_test.zip

**Comment by BeFiveINFO** [comment]
Thank you again!

It now works!

DEXED plays sound, the bug above fixed (combobox), the plugin appears in the Logic Pro UI under the Digital Suburban hierarchy.

There is no failed test during the au validation. There are just warnings.

https://gist.github.com/BeFiveINFO/38316e45b2c251249156

**Comment by BeFiveINFO** [comment]
Dear asb2m10,

As I have enjoyed the AU version of DEXED on logic pro X too much, I ended up with buying a real DX7 (mark I)... Now I find it quite useful to be able to work on both! Thank you!

**Comment by asb2m10** [comment]
Have fun with the DX7 :D AU is now officially supported with Dexed 0.9.0.

**Comment by BeFiveINFO** [comment]
Thank you!!! :)
