### ISSUE TITLE
Installation not working on UbuntuStudio 20.04

### ISSUE THREAD

**Issue by DrAxelbauer** [asb2m10/dexed#221]
I have tried to follow the linux instructions in the README.md.
With the sexond script there seems to be a problem: 
`./scripts/projuce-lin.sh
Re-saving file: /home/benji/dexed/dexed-master/Dexed.jucer
Error when saving: At least one of your JUCE module paths is invalid!
Please go to the Modules settings page and ensure each path points to the correct JUCE modules folder.`
Hence the last script does not work.
Any hints how to install it proberly?

**Comment by tarekmaketechno** [comment]
I got the same issue in Ubuntu 18.04 when I forgot to do a ` git submodule update --init --recursive ` before running any of the scripts. However, I get other errors later in the process and am still unable to build.

**Comment by RohanM** [comment]
I ran into the same problem on vanilla Ubuntu 20.04 and was able to solve it. It appears that there's an inconsistency in where different scripts expect things to be located.

## Quick fix

```
$ mv ../assets .
$ ./assets/JUCE/Projucer --resave Dexed.jucer
```

## More details


```
production/dexed$ ./scripts/get-juce.sh
# ... installs JUCE in production/assets/JUCE
# let's move it into this directory
production/dexed$ mv ../assets .
production/dexed$ cat scripts/projuce-lin.sh
# shows the command needed run JUCE
# but we don't run the exact command, we modify it for having assets in this directory
production/dexed$ ./assets/JUCE/Projucer --resave Dexed.jucer
```

**Comment by asb2m10** [comment]
This was fixed this week, can you do a fresh pull and confirm ?

**Comment by RohanM** [comment]
No joy, unfortunately:

```
$ date
Wed 08 Jul 2020 18:01:24 AEST

$ git clone git@github.com:asb2m10/dexed.git
#...

$ cd dexed
$ git submodule update --init --recursive
# ...

$ ./scripts/get-juce.sh 
# ...

$ ./scripts/projuce-lin.sh 
Could not find file: /home/rohan/production/lv2/Dexed.jucer
```

**Comment by tank-trax** [comment]
this works,,,

```
git clone https://github.com/asb2m10/dexed.git
cd dexed
git submodule update --init --recursive
cd scripts
./get-juce.sh
./projuce-lin.sh
./build-lin.sh
```

**Comment by asb2m10** [comment]
In order for the nightly build to work; the scripts must be ran from the root directory of the project. 

Now the correct way should be : 

```
git clone https://github.com/asb2m10/dexed.git
cd dexed
git submodule update --init --recursive
./scripts/get-juce.sh
./scripts/projuce-lin.sh
./scripts/build-lin.sh
```
