### ISSUE TITLE
No connection to Volca FM via Behringer UMC 1820 audio interface

### ISSUE THREAD

**Issue by walterbelluco** [asb2m10/dexed#224]
DAW: Ableton Live 10 Suite on Windows 10
INTERFACE: Behringer 1820
SYNTH: Korg Volca FM
Won't let me connect to the device. I have tried disabling midi out on Ableton.

**Comment by asb2m10** [comment]
Can you test this with another DAW like Reaper ? otherwise I cannot debug this. Thanks.

**Comment by asb2m10** [comment]
Closing this since no update.
