### ISSUE TITLE
Changes to instructions to reflects changes to scripts

### ISSUE THREAD

**Issue by tank-trax** [asb2m10/dexed#225]
For Linux to build successfully the current instructions cause errors. These were the steps I followed to successfully build the Standalone and VST

```
git clone https://github.com/asb2m10/dexed.git
cd dexed
git submodule update --init --recursive
cd scripts
./get-juce.sh
./projuce-lin.sh
./build-lin.sh
```

for VST2 too

```
git clone https://github.com/asb2m10/dexed.git
cd dexed
git submodule update --init --recursive
cd scripts
./get-juce.sh
export VST2SDK_DIR=~/path/to/vst2/sdk/dir
./projuce-lin-vst2.sh
./build-lin.sh

```

if the current instructions are followed modifications would be required in the scripts to reflect the location where the command is run from matches the locations defined in the scripts

**Comment by RohanM** [comment]
I ran into the same issue from a different angle in #221. I've opened a PR (#226) to make the installation scripts work when their invoked from either directory.

**Comment by asb2m10** [comment]
Sorry about that but I discovered that the scripts needs to be ran from the root directory so the azure pipelines runs. All the script should run if you invoke the scripts from the root directory.

**Comment by baconpaul** [comment]
@tank-trax just merged back into our sst branch also and confirm that we run from the main source directory again. I think you can close this one! And thanks @asb2m10
