### ISSUE TITLE
Standalone linux build failing

### ISSUE THREAD

**Issue by j0nah** [asb2m10/dexed#229]
just following along in the linux install instructions and I get the following:

```
$ ./scripts/build-lin.sh
Compiling include_juce_audio_plugin_client_VST3.cpp
In file included from ../../assets/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp:26:0,
                 from ../../JuceLibraryCode/include_juce_audio_plugin_client_VST3.cpp:9:
../../assets/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3_Wrapper.cpp:66:11: fatal error: pluginterfaces/vst2.x/vstfxstore.h: No such file or directory
  #include "pluginterfaces/vst2.x/vstfxstore.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:187: recipe for target 'build/intermediate/Release/include_juce_audio_plugin_client_VST3_dd633589.o' failed
make: *** [build/intermediate/Release/include_juce_audio_plugin_client_VST3_dd633589.o] Error 1
```

I understand the issues with building the vst2 plugin, but as I understand from the readme, this should just build the standalone version.

**Comment by asb2m10** [comment]
Sorry for the late reply, but you still need to extract the required git submodules (including the VST3 SDK) in order to build it. Let me know if this works for you.

**Comment by LarsMS97** [comment]
I've run into a similar issue:

> ./scripts/build-lin.sh
> Package alsa was not found in the pkg-config search path.
> Perhaps you should add the directory containing `alsa.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'alsa' found
> Package freetype2 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `freetype2.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'freetype2' found
> Package libcurl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libcurl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libcurl' found
> Compiling include_juce_audio_plugin_client_VST3.cpp
> In file included from ../../assets/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client.h:53,
>                  from ../../assets/JUCE/modules/juce_audio_plugin_client/VST3/../utility/juce_IncludeModuleHeaders.h:26,
>                  from ../../assets/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3_Wrapper.cpp:47,
>                  from ../../assets/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp:26,
>                  from ../../JuceLibraryCode/include_juce_audio_plugin_client_VST3.cpp:9:
> ../../assets/JUCE/modules/juce_gui_basics/juce_gui_basics.h:300:12: fatal error: X11/Xlib.h: No such file or directory
>   300 |   #include <X11/Xlib.h>
>       |            ^~~~~~~~~~~~
> compilation terminated.
> make: *** [Makefile:188: build/intermediate/Release/include_juce_audio_plugin_client_VST3_dd633589.o] Error 1

i can find none of the .pc files that are missing from the PKG_CONFIG_PATH on my hard drive.
maybe i just messed up the installation, so here are the exact commands i ran when installing dexed:

> cd ~/vst
> git clone git@github.com:asb2m10/dexed.git
> cd dexed
> git submodule update --init --recursive
> ./scripts/get-juce.sh
> ./scripts/projuce-lin.sh 
> ./scripts/build-lin.sh

**Comment by utopictown** [comment]
@LarsMS97 install libx11-dev https://stackoverflow.com/a/5300030

**Comment by LarsMS97** [comment]
Thanks, I got hung up on the first part of the error message, i didn't even look at the actual part that terminated the compilation x)

For anyone else getting these compiler errors you can just look up the names of the missing header files on debian.packages.org, which will give you a list of packages that include that header.

Specifically, in addition to libx11-dev, i had to install these packages:
libcurl4-gnutls-dev
libfreetype6-dev
libasound2-dev
libxinerama-dev
libjack-jackd2-dev
libxcursor-dev

**Comment by matt32106** [comment]
i made a pull request to update the readme:
https://github.com/asb2m10/dexed/pull/270
