### ISSUE TITLE
wishlist: read/write raw dx7-patches (128 bytes)

### ISSUE THREAD

**Issue by suedwestlicht** [asb2m10/dexed#23]
With Hexter I build up a directory with my favourite sounds. They are single sound files, raw, 128 bytes long. I would be very happy if I could load and write them with Dexed.

**Comment by asb2m10** [comment]
Hi, 

Adding this format is somewhat complicated since it doesn't have any headers and extensions. If you want to use them, I strongly suggest to convert them to DX7 cartridges by using this project : http://dxconvert.martintarenskeen.nl/ 

Then, you will be able to use it with Dexed and Hexter.
