### ISSUE TITLE
Latest nightly crashes on GUI close

### ISSUE THREAD

**Issue by mkruselj** [asb2m10/dexed#232]
Would appreciate a quickfix. Crashes Reaper, Studio One 4, FL Studio, Live 10... could be any host really.

**Comment by asb2m10** [comment]
What is the version on your side ? because the lastest build (Sep 6) doesn't have this behavior.

**Comment by mkruselj** [comment]
Aha it was edc3079-beta, from Aug 20. Let me try the latest nightly!
