### ISSUE TITLE
Use 2x resources for 150% UI scaling

### ISSUE THREAD

**Issue by mkruselj** [asb2m10/dexed#233]
Back at SST Dexed fork I've created 2x UI assets for everything. Here they are:

https://github.com/surge-synthesizer/dexed/issues/49#issuecomment-606081372

Would be really nice to use these assets when 150% UI scaling is selected, in order to not have blurry text etc. Thanks!

**Comment by asb2m10** [comment]
Thanks for this, I've have already render this for implementation and I've got disastrous CPU/GPU readings with JUCE scaling. I didn't want to include it in 0.9.5.

After Dexed 0.9.5 is released I will benchmark and debug the issue with scaling.

**Comment by mkruselj** [comment]
Sounds good - thanks!

**Comment by asb2m10** [comment]
It turns out that the rendering of the amp level of the operators where very CPU expensive when the scaling was other than 100% or 150%. I will have to a do a native rendering, eg not based on an image.

Implementation of this should be done soon !

**Comment by mkruselj** [comment]
I don't think native rendering of that meter should be a problem realistically. 😄 


Thanks for implementing this!

**Comment by mkruselj** [comment]
Hopefully this is still in the cards for happening "soon"? Perhaps 0.9.7?

I'd love to use Dexed at 150% zoom but it's just a blurry mess unfortunately 🙁

**Comment by asb2m10** [comment]
Absolutely, I wish I had time for this but the VST3 automation bug with missing CC was too confusing for users. 

If you wish, you can use the scaling2x branch, not everything is done, but it is way better than the original version. Expect CPU spikes...

**Comment by Lektroid** [comment]
...also 75% would be useful for laptops
