### ISSUE TITLE
Algorithm wiring not refreshed when toggling operators on/off

### ISSUE THREAD

**Issue by mkruselj** [asb2m10/dexed#234]
Currently if you disable an operator and change algorithm, you will see the operator grayed out. But it requires a manual change of algorithm in order to refresh the GUI. It should be an instantaneously applied change. Just misses a GUI refresh when switching the operator toggles.

**Comment by jmkraus** [comment]
Was about to report the same. But I'm not sure if it only a GUI refresh issue. If you switch same operators on/off, you'll get "inverted" GUI visibility:

1. Switch OP2 off --> nothing happens
2. Switch OP2 on --> algorithm shows "OP2 off"
3. Switch OP2 off again --> algorithm shows "OP2 on"

But yes: if you tip on the Algorithm knob, then the display will be corrected.
