### ISSUE TITLE
Instantiate FAILED (DLL contains no VST main entry function) 

### ISSUE THREAD

**Issue by GuidoBartoli** [asb2m10/dexed#235]
I successfully compiled **Dexed** on _Linux Mint 20_ following the [official guide](https://github.com/asb2m10/dexed#linux).
```
Compiling include_juce_graphics.cpp
Compiling include_juce_gui_basics.cpp
Compiling include_juce_gui_extra.cpp
Compiling include_surgesynthteam_tuningui.cpp
Linking Dexed - Shared Code
Linking Dexed - VST3
Compiling include_juce_audio_plugin_client_Standalone.cpp
Linking Dexed - Standalone Plugin
```
I used **Renoise** as a host for the VST3, but when the instrument is loaded I receive this error in the log:
```
Renoise LOG> VstPlugs: Trying to instantiate /home/guido/.vst3/Dexed.vst3/Contents/x86_64-linux/Dexed.so
Renoise LOG> VstPlugs: Instantiate FAILED (DLL contains no VST main entry function) !!!
```
Any idea about what is the cause?

Many thanks,
Cheers

**Comment by asb2m10** [comment]
I've double check and Renoise doesn't support VST3 yet. If you can find and old VST2 sdk and recompile with it (see instruction at the bottom of the README.md), it should work out of the box.

**Comment by GuidoBartoli** [comment]
Thanks, I did not notice that I compiled it with a VST3 SDK.
