### ISSUE TITLE
Dexed Standalone Crackling

### ISSUE THREAD

**Issue by jfowkes** [asb2m10/dexed#236]
First of all, thank you for this amazing DX7 synth! 

I'm having an issue with the standalone version of Dexed on Linux with ALSA: playing bass notes (e.g. using preset 04 PHAROH) using either the Mark I or OPL engine results in audible crackling irrespective of the Audio Buffer Size. An audible crack is also heard when changing engines. This is using the latest nightly build on my desktop. The exact same issue occurs with 0.9.4 built from source. Is anyone else able to reproduce this?

**Comment by asb2m10** [comment]
If you hear crackling only when pressing the bass notes of PHAROH, that's work as design since the DX7 does the same.

As for the audible crack when changing the engine that part was not designed to be switch in realtime.

**Comment by jfowkes** [comment]
Oh really, is that the case with all patches then? For example I also hear bass note crackling on E PIANO 1.

Guess I'll have to dig my DX7 out of the garage and listen to it carefully :)

**Comment by shooking** [comment]
> If you hear crackling only when pressing the bass notes of PHAROH, that's work as design since the DX7 does the same.
> 
> As for the audible crack when changing the engine that part was not designed to be switch in realtime.

Great to know - I was messing with buffers etc on my Pi4 thinking maybe it was just underpowered or the USB audio couldn't work. You saved me a lot of diagnostic - thanks.

Great product - my Pi4 thanks you for letting it live.
I was wondering if it would be ok to make a pull request to build Pi? My video is here https://youtu.be/9IUUzV516kQ. I left all the steps in the description - first time I ever got Projucer working (once I build it :-)). Really helping me out with Ctrlr too. Great stuff you are doing here.

**Comment by jfowkes** [comment]
> I was wondering if it would be ok to make a pull request to build Pi? My video is here https://youtu.be/9IUUzV516kQ. I left all the steps in the description - first time I ever got Projucer working (once I build it :-)). Really helping me out with Ctrlr too. Great stuff you are doing here.

Thanks for the great tutorial! I also build Dexed on a Pi4 so a pull request would be great.

**Comment by asb2m10** [comment]
I don't think you don't need a pull request to enable Pi4 builds. The Dexed wiki pages are public and you are welcome to add the documentation for the Pi4 build.
