### ISSUE TITLE
Automation not working on Reaper

### ISSUE THREAD

**Issue by alfonso73** [asb2m10/dexed#244]
Hi, i've just installed 0.9.5. I see all the VST3 parameter list but
1. Automation does not work 
2. There's no way to arm a VST parameter by touching the relevant knob or control on Dexed GUI

**Comment by asb2m10** [comment]
Hi,

I've fixed the automation bug. Please test it with the nightly build. I was able to arm the parameter with Live and Bitwig. Let me know if still have the issue.

**Comment by alfonso73** [comment]
Hi @asb2m10, thanks! Where can i find the nightly build?

**Comment by asb2m10** [comment]
https://github.com/asb2m10/dexed/releases/tag/Nightly

**Comment by alfonso73** [comment]
@asb2m10 Thanks. Almost ok now. In "Touch" mode in Reaper while moving parameters on Dexed GUI it seems that even if it a knob is touched it always return to its initial position. A kind of writing/reading automation feedback problem (other VST in Reaper works fine with Touch mode to)

**Comment by asb2m10** [comment]
Ok, I will have to test this with the Repear workflow.

**Comment by alfonso73** [comment]
@asb2m10 Check the "Touch" automation mode
