### ISSUE TITLE
Ratio & Fixed switch bug.

### ISSUE THREAD

**Issue by realistortion** [asb2m10/dexed#245]
In the recent VST3 release, switching from Ratio to Fixed and viceversa requires you to move the tuning knobs (tune, coarse, fine) for the frequency display to change. Otherwise it stays as the default setting (ie. f=1 when it should be displaying hertz instead)

**Comment by asb2m10** [comment]
Yes, there were an automation issue with VST3; I've just fixed it. Please try the latest nightly build.
