### ISSUE TITLE
Mod wheel not working.

### ISSUE THREAD

**Issue by realistortion** [asb2m10/dexed#246]
Mod wheel non responsive when trying to add pitch modulation. Tried the same patch with the same settings on the stable build of Dexed. Works fine, but not in the latest build.

**Comment by asb2m10** [comment]
Sorry, but I'm unable to reproduce this. What patch where you testing ?

**Comment by realistortion** [comment]
Self made patch. I work both with the stable Dexed version and the latest build, sometimes interchangeably. Could that be the issue?

**Comment by mkruselj** [comment]
Send patch?

**Comment by realistortion** [comment]
> Send patch?

Apologies for the delay. Also, not sure if you can extract a single preset and not the entire cartridge in Dexed, so I'll send the whole file. Preset in nº 26, DynoRhodes

https://drive.google.com/file/d/1TYZ9TDpKXBxp1Q9DRgmuh9slfgXfGm7d/view?usp=sharing

**Comment by mkruselj** [comment]
Can you please just pack that cartridge in a ZIP and drop it here, rather than using Google Drive? You have removed the file from your GDrive so I can't check it out...

**Comment by realistortion** [comment]
I just checked the preset with the latest build, and the issue is gone. However, the standalone can't seem to recognize ASIO devices, only the Windows built in ones. I guess close the thread?

**Comment by mkruselj** [comment]
Yeah, cannot have ASIO on GPL3 software unfortunately unless you build from source yourself and have signed a contract with Steinberg to get the ASIO SDK...

**Comment by realistortion** [comment]
Oh damn, didn't know that. Well, issue solved.
