### ISSUE TITLE
How do I install on Ubuntu?

### ISSUE THREAD

**Issue by CHJ85** [asb2m10/dexed#248]
Hi there. I couldn't find any documentation on how to install this on Linux.
The readme file only covers Windows and Mac installation.
Where do I put the 2 files that came in the linux zip file (Dexed and x86_64-linux) ?
The readme file said that there are 3 .sh files in a Scripts folder which wasn't included in the zip file. Only the 2 files I mentioned

**Comment by utopictown** [comment]
pull this repo and build it yourself

> Hi there. I couldn't find any documentation on how to install this on Linux.
> The readme file only covers Windows and Mac installation.
> Where do I put the 2 files that came in the linux zip file (Dexed and x86_64-linux) ?
> The readme file said that there are 3 .sh files in a Scripts folder which wasn't included in the zip file. Only the 2 files I mentioned

pull this repo and build it yourself

**Comment by shooking** [comment]
You should be able to build it from scratch as the Projucer shipped with Linux of for 64bit Linux.
They give the steps on main git page.
Pull the dexed
Run the 3 scripts ... Should build.

I made a YT on how to build on Raspberry Pi.it has all the steps in the description. Of course you wouldn't have to build the Projucer nor edit the makefiles.
Having said that if you wanted to run Dexed of a Pi (I want to embed it into a midi controller keyboard) then a Pi 4 makes a decent platform
https://youtu.be/9IUUzV516kQ

**Comment by asb2m10** [comment]
I've updated the Dexed wiki for Linux:

https://github.com/asb2m10/dexed/wiki/Installation

**Comment by CHJ85** [comment]
thank you
