### ISSUE TITLE
Show Breakpoint parameter in actual note values, not numbers

### ISSUE THREAD

**Issue by mkruselj** [asb2m10/dexed#25]
It will be easier to know to which key you've actually set those breakpoints then! :)

**Comment by asb2m10** [comment]
Yes, I know, that was part of my internal TODO. Will be done in 0.8.1.

**Comment by asb2m10** [comment]
Fixed in Dexed 0.9.0

**Comment by Sentinel77** [comment]
Hi,


I think this issue could be reopened.

Note names were implemented nicely for parameter 'Middle C Transpose'.

But still need note names (A-1 to C8) for OP 1-6 'Break Point'.

Might also be good if the break point INIT value was set to '0' (A-1) as with the Dx7. Currently the dexed default is 39.


Thank you.
