### ISSUE TITLE
Missing file on installation

### ISSUE THREAD

**Issue by SpauldingSparks** [asb2m10/dexed#250]
Trying to use Dexed as a VST plugin in Ableton live standard. Each time I've tried to install, it is missing the ".dll" file that would  allow Ableton to read it. It's working fine as a standalone app, but the .dll is nowhere to be found. I have also been unable to find the file by itself anywhere on the internet. What could cause this, and how could it be fixed?

I am very new to coding, so I am unsure what could be going wrong. Every other VST I've downloaded has worked no problem.

Any help would be appreciated!

**Comment by RyushoYosei** [comment]
This is actually what I was just tryinng to figure out myself as I was installing it to use in LMMS and there is no .dll file.

**Comment by groovile** [comment]
Same here. I don't think it asks me where to install the .dll either, only the program.

**Comment by asb2m10** [comment]
As a VST, only the VST3 is provided and this file ends with ".vst3"

VST2 ends with ".dll" but it is not distributed anymore because of licensing issues with Steingberg.

Thank you for your understanding.

**Comment by Andy2No** [comment]
Where is the VST3 file, or any other form of VST, in Windows?  Where is it placed?

My DAW (Cantabile) only seems the VST2 DLL from 0.9.3, which I installed previously.  After installing 0.9.5, it can't see it, and I see nothing telling me where it should be.
