### ISSUE TITLE
[Feature request] StudioRack integration

### ISSUE THREAD

**Issue by kmturley** [asb2m10/dexed#251]
I'm the lead developer of an open-source VST plugin manager called StudioRack:
https://github.com/studiorack

The aim of my project is to provide a free open-source way to manage VST plugin dependencies and their versions. I would love to add Dexed to the StudioRack Registry, which would involve the following steps:

1. Publish a Github release containing the plugin source along with metadata plugins.json
2. Tag your Github repository with studiorack-plugin so it can be discovered
3. Wait for the studiorack-registry to index your plugin (every 24 hours)
4. Check the registry feed for your plugin to appear https://studiorack.github.io/studiorack-registry/

Wondering if you would be interested in collaborating to make this work? It would then allow users to install Dexed using the StudioRack website, command-line tool or app?

Thanks!

**Comment by asb2m10** [comment]
I see that Dexed is now integrated to StudioRack (cool project btw). I guess nothing is required on our side so I can close this issue.
