### ISSUE TITLE
Context menu broken again on Mac?

### ISSUE THREAD

**Issue by giacecco** [asb2m10/dexed#253]
Hi All, despite [this change back in 2017](https://github.com/asb2m10/dexed/commit/d522d84d89e0017e442b19664cc2ceee5b42e337), I have no context menu in macOS today in dexed 0.9.5 . Is it just me? Thanks.

**Comment by giacecco** [comment]
Same in 0.9.4 . I went back to the older version because it feels generally better, given the series of issues I have had with 0.9.5.

**Comment by asb2m10** [comment]
I've tested this with my two macOS (Catalina and Sierra) and was able to see the context menu. What version of macOS are you using ?

**Comment by giacecco** [comment]
Catalina, 10.15.7. The issue happens with both the Macbook Pro's own trackpad and the external Magic Trackpad 2. The MacBook is a MacBook Pro (16-inch, 2019). The issue is localised to a few functions where the context menu should be, such as copying and pasting envelopes. But the context menu works elsewhere, e.g. in the cart management, where I can see it.

**Comment by asb2m10** [comment]
I am unable to reproduce this on macOS.
