### ISSUE TITLE
"tune" instead of "det" on macOS for the first encoder of each operator

### ISSUE THREAD

**Issue by giacecco** [asb2m10/dexed#254]
Hi All. I am in the middle on some training that uses dexed, and my professor's dexed on Windows looks like in the video on the homepage: each operator's encoders are det, coarse and fine. But on dexed 0.9.5 for macOS I see tune, coarse and fine instead. The encoder also looks like it not doing anything but changing the display at the top (f = 1 +1/2/3...).

**Comment by mkruselj** [comment]
That's indeed how it is in the latest versions, the parameter is more properly named now.
