### ISSUE TITLE
Algorithms operator on / off display broken

### ISSUE THREAD

**Issue by giacecco** [asb2m10/dexed#256]
Hi All, displaying if operators are on or off in the algorithm display at the bottom of the UI seems to be broken. To reproduce, in Dexed 0.9.5 for macOS, do for example this:

1) start Dexed
2) turn operator 1 off, and see that the operator 1 still looks like it is on in the algorithm display
3) turn operator 1 back on, and see that operator 1 shows now as off in the algorithm display
4) use the mouse and click on 1 in the algorithm display, and the display will show the actual status as on

**Comment by asb2m10** [comment]
This was a known issue and it is fixed (#234) in the nightly builds.
