### ISSUE TITLE
RPI 4 - Exec format error

### ISSUE THREAD

**Issue by phil123456** [asb2m10/dexed#257]
Hello,

has anyone tried compiling under raspberry pi ?

I get an error , which I suspect is related to the ARM architecture

    pi@raspberrypi:~/dexed $ ./scripts/projuce-lin.sh
    ./scripts/projuce-lin.sh: 4: ./scripts/projuce-lin.sh: assets/JUCE/Projucer: Exec format error

is it possible to solve this ?

thanks

**Comment by phil123456** [comment]
ok nevermind I finaly found out how to build this

**Comment by shooking** [comment]
Glad to hear you fixed it.
I made a video on how to build Dexed on a Pi4.

I also ran into the Projucer issue. add atomic library, build Projucer. Use that to open the Dexed.jucer and add in the necessary external libraries. A little while later and one can run a DX7 voice on a Pi4. cool

https://youtu.be/9IUUzV516kQ
