### ISSUE TITLE
macOS build failed

### ISSUE THREAD

**Issue by marklit** [asb2m10/dexed#258]
I'm running Big Sur and Xcode 12.3.

These were the steps I took:

```bash
$ git clone https://github.com/asb2m10/dexed.git
$ cd dexed
$ sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
$ git submodule update --init --recursive
$ scripts/get-juce.sh
$ scripts/projuce-mac.sh
$ scripts/build-mac.sh
```

This was the failure message that resulted:

```
...
** BUILD FAILED **


The following build commands failed:
	CompileC build/Dexed.build/Release/Dexed\ -\ Shared\ Code.build/Objects-normal/arm64/include_juce_audio_devices.o /Users/mark/Downloads/dexed/JuceLibraryCode/include_juce_audio_devices.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by asb2m10** [comment]
There is no support for ARM based computer. Maybe try upgrading the JUCE version. 

Modify this: scripts/get-juce.sh
`JUCE_VERSION=6.0.5`

Let me know if this works.

**Comment by marklit** [comment]
Sorry, I didn't mention that I'm on an Intel-based system.

Upgrading JUCE to 6.0.5 did the trick, thank you.

I've raised a pull request with this patch: https://github.com/asb2m10/dexed/pull/259
