### ISSUE TITLE
Inquiries about SysEx dedicated to dx7ii

### ISSUE THREAD

**Issue by yumenekosoft** [asb2m10/dexed#262]
Hello

KV-101生福天の巻
KV-102生福地の巻

I need to use this cartridge, but Dexed doesn't seem to be working properly.

Do you have a patch plan for the SysEx file dedicated to DX7II?

(If patch is not possible, is there another alternative?)

**Comment by asb2m10** [comment]
For now Dexed only works with the original Mark I cartridge, supporting the extended version means also supporting the storage which can be more tedious than expected.

If you need to work with those extended cartridges, you can use http://dxconvert.martintarenskeen.nl/ that can convert most of the DX familly cartridge to the DX7 Mark I.
