### ISSUE TITLE
Program Change messages not working.

### ISSUE THREAD

**Issue by FineArtMaths** [asb2m10/dexed#264]
I can't get Dexed to respond to program change messages. I'm only able to test the latest version in REAPER so not sure how localized this is.

From a blank REAPER project I've tried:

* Inserting a program change message in the clip and playing it
* Firing a program change message from the built-in script MIDI Program Change / Bank Switch on Load
* Firing a program change message from my own JSFX script

None of these has any effect on Dexed. I've confirmed that all these work with all the VSTis I regularly use (AAS stuff, Pianoteq) but Dexed seems to ignore them.

I wanted to take this opportunity to thank you for adding microtuning support. This is an absolutely huge deal for those of us who care about it, and it's enabled me to integrate Dexed back into my setup (hence this request...).

**Comment by asb2m10** [comment]
Closing this since it is a duplicated of #266
