### ISSUE TITLE
warning: overlapping comparisons always evaluate to false

### ISSUE THREAD

**Issue by rd--** [asb2m10/dexed#271]
hello

clang-11.0.1 reports:

msfa/controllers.h:52:23: warning: overlapping comparisons always evaluate to false [-Wtautological-overlap-compare]
        range = r < 0 && r > 127 ? 0 : r;

which seems correct.

i guess it should be r < 0 || r > 127?

best,
rohan

**Comment by asb2m10** [comment]
Yes you are right ! Thanks !
