### ISSUE TITLE
VST2 Mac build 

### ISSUE THREAD

**Issue by waterjump** [asb2m10/dexed#275]
I'm in the process of moving my music production environment to a new machine (a Mac).  I have old projects that use the VST2 version of Dexed, and while the VST3 version of Dexed works fine for new projects, existing projects that use the VST2 version will raise a missing plugin error.  

I took a look at the linux VST2 build in the hopes it would be Mac compatible but it fails on the following step: 
``` ./scripts/projuce-lin-vst2.sh```
Error: 
```./scripts/projuce-lin-vst2.sh: line 13: assets/JUCE/Projucer: No such file or directory```

Is it possible to create a Mac-specific VST2 build for legacy purposes, or maybe tweak the linux version to be Mac compatible?  Thanks.

**Comment by asb2m10** [comment]
Please check the latest version (and README.md), you simply have to set VST2SDK_DIR and it should work. Let me know if it doesn't for you.
