### ISSUE TITLE
Improving documentation

### ISSUE THREAD

**Issue by ajxs** [asb2m10/dexed#280]
Hello,
Thanks for the amazing emulator! 
Would you be open to me making a PR with some inline documentation for the Mk1 engine code?
I've been going through the source code from the ground up in an effort to understand how the DX7 (maybe) works. I've written a bunch of documentation for the code as I go, this is mostly just clarifying what pieces of the code do. I think there may be a few minor inaccuracies in some of the variable names. Not anything serious, just things inherited from MSFA.

**Comment by mkruselj** [comment]
By all means do send a PR!

**Comment by asb2m10** [comment]
Like @mkruselj said, PR are very welcomed.
