### ISSUE TITLE
0.9.6 installation

### ISSUE THREAD

**Issue by CNg2021** [asb2m10/dexed#283]
On PC Windows 10.
If installation selects both StandAlone.exe and VST, only Standalone is installed.
The work around is to install again with ONLY VST selected.

**Comment by CNg2021** [comment]
Actually, it does not install the VST dll at all, regardless of what selections choices at point of installation.

**Comment by kpd328** [comment]
It installs itself to %ProgramFiles%\Common Files\VST3\Dexted.vst3, not the main program directory.

**Comment by asb2m10** [comment]
Yes this is the standard with VST3.
