### ISSUE TITLE
TX802 patch compatibility

### ISSUE THREAD

**Issue by dbogdanov** [asb2m10/dexed#29]
I am trying to use Dexed with a [DX7 200K patch collection](http://korgpatches.com/patches/kronos/dx7_200k_collection).

However, patches for TX802 are not loaded properly (strange patch names, no sound or erroneous sounds). I though TX802 are compatible with DX7 patches. I am planning to used Dexed together with my hardware TX802.

**Comment by asb2m10** [comment]
The TX802 sysex aren't the same as the DX7 one. If I can find documentation about the TX802 sysex format the conversion should be too difficult to do. I will address this after the version 0.9.0.

**Comment by asb2m10** [comment]
Duplicate #165
