### ISSUE TITLE
MIDI Learn doesn't recognize CC64

### ISSUE THREAD

**Issue by xeniera** [asb2m10/dexed#293]
Version 0.9.6, Windows 10

Using an Alesis VI61 MIDI controller.  When trying to use the MIDI Learn feature, CC64 sent by my controller is not recognized on any channel.  CC63 and CC65 work.

**Comment by asb2m10** [comment]
Sorry for the late reply but this is the sustain pedal cc, it cannot be map to a controller since it is a global synth message.
