### ISSUE TITLE
TX81Z Compatibility.

### ISSUE THREAD

**Issue by Atekuro95** [asb2m10/dexed#295]
I love the tx81z with its lately bass preset. but will the dexed be compatible with the tx81z?

**Comment by MBYlt** [comment]
The TX81Z uses a completely different patch structure from the DX7. The TX81Z is 4-op, 8 waveform; versus 6-op, 1 waveform on the DX7; and the SysEx for each is completely different. Apples and oranges. TX81Z compatibility would be way outside spec.

You'd probably want something like [discoDSP Phantom]](https://www.discodsp.com/phantom/)

**Comment by bryc** [comment]
Was already suggested here: https://github.com/asb2m10/dexed/issues/163

**Comment by asb2m10** [comment]
I understand that it would be great to have a hybrid DX7/TX81Z engine but this requires a lot of work to assure compatibility with the originals. I want to work on the DX7 first.
