### ISSUE TITLE
how to control the whole keyboard with the computer keyboard

### ISSUE THREAD

**Issue by JOSEA309** [asb2m10/dexed#296]
I would like to know how I can control the entire computer keyboard, since it only leaves me from the scale c4 to c5

**Comment by asb2m10** [comment]
Hi,
If you want more control (more keys) on the computer keyboard, I really suggest you use a dedicated DAW/plugin host that can do this like https://www.hermannseib.com/english/savihost.htm with dexed as a plugin.
