### ISSUE TITLE
Pretty names for VST3 parameters ?

### ISSUE THREAD

**Issue by jcelerier** [asb2m10/dexed#301]
Hello,
I am trying to make Dexed work correctly in my VST3 host, [ossia score](https://ossia.io).

I have this code called when I move a controller in the Dexed UI: 

```C++
void Model::addControlFromEditor(
    Steinberg::Vst::ParamID id,
    Steinberg::Vst::ParamValue valueNormalized)
{
  Steinberg::Vst::ParameterInfo p;
  if(fx.controller->getParameterInfo(paramIdToIndex(id), p) == Steinberg::kResultOk)
  {
    qDebug() 
     << QString::fromUtf16(p.title)
     << QString::fromUtf16(p.shortTitle) 
     << QString::fromUtf16(p.units);
  }
}
```
 
which prints me for most parameters (except Output FEEDBACK, ALGORITHM, LFO SPEED and a couple ones)
```
"MIDI CC 12|12" "" "" 
```
(with the CC changing depending on the parameter).

Do you have any idea of how I could get the proper parameter names as with the VST2 version instead of these MIDI CC things ? Other VST3 plug-ins I tried (Vital, the Steinberg examples) seem to give me correct names but I guess there's some IBlablaHandler that I haven't implemented... thanks !

**Comment by asb2m10** [comment]
Hi, 

Yes, this might be the limitation of VST3 and midi CC automation sync with JUCE. Try compiling the project with the option JUCE_VST3_EMULATE_MIDI_CC_WITH_PARAMETERS=0. This broke VST3 automation with Live and Reaper, I had to remove this option. See #244 

Let me know if this works.

Thanks.

**Comment by jcelerier** [comment]
hi, okay if this is an expected behaviour I don't mind, I just don't want users of my host to have a subpar experience when compared to other hosts. thanks !
