### ISSUE TITLE
Provided Linux build procedure does not work on non-x86 architectures

### ISSUE THREAD

**Issue by diodelass** [asb2m10/dexed#305]
Trying to build Dexed according to the provided instructions does not work on ARM, because the `Projucer` binary downloaded by `get-juce.sh` is for x86_64, and cannot be run by `projuce.sh`:
```
Generating build for VST3
./scripts/projuce.sh: line 16: assets/JUCE/Projucer: cannot execute binary file: Exec format error
```

Fortunately, it is still possible to build Projucer from source, and I was able to get Dexed built and working by replacing ./assets/JUCE/Projucer with the recompiled binary. So for the complete build process:
```
https://github.com/asb2m10/dexed
cd dexed
git submodule update --init --recursive
./scripts/get_juce.sh

cd ..
git clone https://github.com/juce-framework/JUCE
cd JUCE
cmake . -B cmake-build -DJUCE_BUILD_EXTRAS=ON  # takes a long time
cmake --build cmake-build --target Projucer    # takes a very long time
cp cmake-build/extras/Projucer/Projucer_artefacts/Projucer ../dexed/assets/JUCE/Projucer   # overwrites x86 Projucer binary

cd ..
cd dexed
./scripts/projuce.sh  # should actually work now
./scripts/build-lin.sh
```
And if all goes well, a working binary should be dropped in `Builds/Linux/build/Dexed`.

It seems that nothing about support for Linux on ARM here is actually broken, and it's just the build system not making any attempt to detect or work with non-x86 architectures. Once I'd stumbled my way into this solution, I was able to compile a working binary of Dexed on my Pinebook Pro running Manjaro, and it works excellently connected to my keyboard via USB with Pipewire (emulating JACK) as the audio backend. Since there are a lot of ARM devices like this with favorable characteristics for audio work - especially the Raspberry Pi series, which see a lot of artistic use - I think it would be worth providing documentation to build Dexed on other architectures besides just x86. I opened an issue instead of making a pull request, though, because I have never encountered Juce before and have no idea what the most appropriate way to streamline the build process here would be. This is a solution that works, but it compiles a huge amount of extra code that isn't really needed, so it would be great if there were a way to avoid having to completely rebuild Juce and Projucer. 

At the very least, my hope is that this issue will be found by web searches for this problem when people who are relatively new to Linux try to build Dexed on their Raspberry Pi, just to us something to work with, but I do think that it would be really helpful and worthwhile for someone familiar with this build system to come up with a cleaner solution.

**Comment by asb2m10** [comment]
On 0.9.7 I will move forward on cmake that will no longer require Projucer. Keeping this open until the build on cmake is working.

**Comment by asb2m10** [comment]
Please use CMake to build Dexed, it should now work out of the box: https://github.com/asb2m10/dexed/blob/master/README_cmake.md
