### ISSUE TITLE
Reface DX mode

### ISSUE THREAD

**Issue by jrmoserbaltimore** [asb2m10/dexed#307]
Just a feature request for a Reface DX mode somewhere down the line, since I hear there's an OPL mode.

The Reface DX is a stand-alone 4-op FM synthesizer available for like $300, which makes it plenty accessible for people looking to get into FM synthesis.  It has an online library on Soundmondo, which automatically connects to a MIDI device to program the Reface DX; Dexed could also act as a MIDI device and expose itself as a Reface DX for this purpose.

This would thus be a low-budget path for people to use e.g. OpenMPT (which still only supports VST2, though) with instruments compatible with a portable hardware synthesizer keyboard.

**Comment by asb2m10** [comment]
Hi thanks for the interest but this synth is based on the DX7. The OPL mode is used to mimic the math limitation of the OPL chip, it is not a freeform 4op synth.
