### ISSUE TITLE
Error when saving: At least one of your JUCE module paths is invalid!

### ISSUE THREAD

**Issue by Peppitox** [asb2m10/dexed#309]
So I tried to compile it for Ubuntu 20.04 but I got this error 

$ ./scripts/projuce.sh
Generating build for VST3
Re-saving file: /home/poppy/PoppyOS/Apps/Git/dexed-master/Dexed.jucer
Error when saving: At least one of your JUCE module paths is invalid!
Please ensure each module path points to the correct JUCE modules folder.

**Comment by iwrotesomecode** [comment]
I ran into this on Ubuntu 21.10, but a working solution has already been addressed in https://github.com/asb2m10/dexed/issues/221
In the `dexed` folder run `git submodule update --init --recursive` before running `./scripts/projuce.sh`

**Comment by RingoManju** [comment]
FWIW I had the same error on macOS Monterey, and the same fix from @iwrotesomecode worked for me (BUT only if I downloaded the source code via `git clone`)

**Comment by asb2m10** [comment]
I'm closing this since ProJucer is no longer required (cmake is now the standard).
