### ISSUE TITLE
Hanging notes

### ISSUE THREAD

**Issue by JurekRaben** [asb2m10/dexed#31]
Hi,

if I use some Dexed 0.80 instances, after a while there is some kind of hanging notes, a very quiet endless tone. Using multiple instances will result in a louder hanging tone.

All instances had note-offs at the end. Only midi reset helps.

Please fix.

**Comment by asb2m10** [comment]
Hi

The DX7 does that too on certain programs/preset; what program are you using so I can reproduce it on my side ?

**Comment by JurekRaben** [comment]
Ok i will build a demo in renoise 3, you can play it then using the free demo version.

**Comment by JurekRaben** [comment]
Hi Pascal,

here is a test package for hanging notes:
http://tstlab.virtualcreations.de/dexed080-hangingnotes.zip

Inside are two presets that produce hanging sounds. Maybe it's not so audible, so maybe use an analyzer to see it. In case you cannot reproduce, please load the included renoise song in renoise 3.01 and play it until the end. You can also use Renoise as FFT analyzer, it has a very good and precise one.

Greetings.

**Comment by asb2m10** [comment]
Hi,

In the Renoise example you gave me, both presets of both tracks didn't had :

* EG Level 4 = 0
* EG Rate 4 = 99

If you want to stop the audio once you have released the note, you need to set that settings on all carriers (operator that output sound) otherwise you might have undesired leftovers like you had.

- Regards

**Comment by JurekRaben** [comment]
Hm, maybe you are correct from a technical point of view and the original dx7 would have the same behavior.

But this is an engine design error/problem, in my opinion. I also doubt that fm8 would produce hanging notes in such a case. Can't you include an algorithmic prevention of such a case? please keep in mind, not everybody using it is a dx7 parameter expert. and a bunch of freely available presets would have this problem, too.

**Comment by asb2m10** [comment]
An algorithmic prevention could also block something that the user really wants... the line between what the user wants and what the user expect can be pretty thin.

Sorry, but this emulation replicate what the DX7 does; including it's flaws and also for some users it's strengths.
