### ISSUE TITLE
Loading sysex

### ISSUE THREAD

**Issue by jprykiel** [asb2m10/dexed#312]
Hello,
I am new to DEXED, and tried to load previously saved  banks from my good old DX7 2FD into this promising plug-in.
When I click the load button, browse to the desired file and validate, I get the following error message  
"Unable to find DX7 sysex cartridge in file ...
I tried this with single sounds or banks previously saved from the original device via midi bulk. I still have the DX7 2FD, but but have not found a way to transmit data from a physical cartridge via MIDI.
The only thing I can do is load the cartridge contents to my internal sounds and then bulk them.
Is there a way?
Thanks,
JPR

**Comment by asb2m10** [comment]
For now Dexed only works with the original Mark I cartridge, supporting the extended version means also supporting the storage which can be more tedious than expected.

If you need to work with those extended cartridges, you can use http://dxconvert.martintarenskeen.nl/ that can convert most of the DX familly cartridge to the DX7 Mark I.
