### ISSUE TITLE
Audio extremely low

### ISSUE THREAD

**Issue by markaudacity** [asb2m10/dexed#314]
On macOS 10.14.6, Dexed is outputting audio at an extremely low level on all audio interfaces with the LEVEL knob set to max. 
The output VU meter is showing a level that corresponds to the level of audio heard, while the level meters for the individual operators are peaking at full range as expected.

This occurs independent of what patch is loaded. I loaded the Init patch to verify it wasn't patch-related, and the behavior does not change.

<img width="868" alt="Screenshot 2021-10-07 at 12 11 16" src="https://user-images.githubusercontent.com/62250787/136432138-2205ecb6-d940-4fad-b27d-2605ea80fba9.png">
.

**Comment by asb2m10** [comment]
This is unusual. Can you share the cartridge so I can test this on my side ?

**Comment by asb2m10** [comment]
I am closing this since I didn't have feedback.
