### ISSUE TITLE
Slow performance w/Ableton?

### ISSUE THREAD

**Issue by jdelman** [asb2m10/dexed#315]
First, thank you for this AMAZING piece of software.

I'm using Dexed with Live 11 on Mac OS 10.14.6. My Mac runs in "retina" (2x) mode. I've noticed that when I have the Dexed control panel open, Ableton starts to get quite laggy, and the inteface itself is a bit slow. Is there anything I can do from a hardware acceleration / CPU usage perspective to improve performance?

**Comment by asb2m10** [comment]
Thanks !

Yes, I'm very aware of this and it will be fixed with 0.9.7. Keep scaling to 100% for now to keep CPU low.

Reference #128 and #233
