### ISSUE TITLE
macOS’ Dexed.app has unchanging version numbers

### ISSUE THREAD

**Issue by vitorgalvao** [asb2m10/dexed#316]
To accurately display version information, macOS apps need to have the `CFBundleVersion` and `CFBundleShortVersionString` tags in `Info.plist`.

In `Dexed.app` they’re at a fixed `1.0.0` instead of the release number. If numbers are not set during the build process, they can be changed after it’s done by directly editing the `Info.plist`:

```bash
# Change these values
app_path='/PATH/TO/APP/HERE'
app_version='VERSION NUMBER HERE'

# Keep these as they are
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion string ${app_version}" "${app_path}/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString string ${app_version}" "${app_path}/Contents/Info.plist"
```

That would use the same version number for both fields. Technically they should be different, but even having both the same would be a major improvement.

Accurate versions numbers are important for macOS to know which app to open in ambiguous situations; for users (who expect to see them in the Finder); and for accurate interoperability with other apps.

**Comment by asb2m10** [comment]
There is a historical reason behind this. Changing the version to 0.9.x actually breaks plugin DAW compatibilities. Until Dexed version is below 1, I will have to keep this. But once we get to 1.0, the version will be set accordingly.
