### ISSUE TITLE
Chosen patch changes to first/last listed patch in ROM upon playback (Logic Pro X 10.5.1)

### ISSUE THREAD

**Issue by Legosi13** [asb2m10/dexed#318]
Long story short: When I choose the patch desired, it selects it. However, once I want to listen the track I assigned Dexed to with said desired patch, it changes it to the first/last (varies between the two) listed patch within the chosen ROM, regardless whether associated automated settings were wiped or not.
![nedb4s71ygy71](https://user-images.githubusercontent.com/67709387/140860127-6c2de832-4065-493b-8da7-c11fb022123f.png)
This might not appear in order but basically I want "BRASS 1" but changes it automatically to "TAKE OFF" upon playback for no explained reason.
![oa4f9s71ygy71](https://user-images.githubusercontent.com/67709387/140860216-c21083f4-bcbf-45ad-8121-eb20ecc862f9.png)

**Comment by asb2m10** [comment]
Unable to reproduce this. Do you have a minimal Logic project that has this behaviour ?

**Comment by Legosi13** [comment]
I believe I've solved the issue in that, the MIDI (which was pre-made/downloaded) may've contained some incompatible or specific parameters Dexed was forced to read and referred to it, but perhaps I can provide a project file as well as an example. Call me dumb but, is there a way to rid a track of that strange "00" marking that way it doesn't affect my preferences for Dexed
<img width="1322" alt="Screen Shot 0003-11-12 at 20 53 45" src="https://user-images.githubusercontent.com/67709387/141601763-de101f50-64c8-4362-9ff0-aaa56fb17bfe.png">
d?

https://drive.google.com/drive/folders/1F-SeuV9q1g0AkgU6uX2WBVXb8EM0jPBT?usp=sharing the demo file

Thanks again for taking the time,
Mokusei
