### ISSUE TITLE
Sliders not showing in PARM window.

### ISSUE THREAD

**Issue by caoliver** [asb2m10/dexed#32]
I'm running Dexed 0.8.0 under linux.  Everything seems fine except that there is nothing on the PARM window save for OK and Cancel.  I wind up needing to edit the Dexed.xml file by hand to change these things.

**Comment by asb2m10** [comment]
I've never seen that problem. What build are you using ? Did you tried to build the latest branch 'work-0.8.1' ? Also, did you used another host (like JUCE PluginHost) ? And if it is easy for you, you could try another window manager.

**Comment by caoliver** [comment]
On Mon, 06 Apr 2015 21:17:51 -0700
Pascal Gauthier <notifications@github.com> wrote:

> I've never seen that problem. What build are you using ? Did you tried to build the latest branch 'work-0.8.1' ? Also, did you used another host (like JUCE PluginHost) ? And if it is easy for you, you could try another window manager. 

This is not trivial for me.  I run the pluggin as LV2, not VST.  You don't build that way out of the box.  I tried 0.8.0 under jalv.qt under xephyr without any window manager, and the same thing happens.  The widgets are not being rendered.

> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/asb2m10/dexed/issues/32#issuecomment-90353845


-- 
Christopher Oliver <caobizz@gmail.com>
