### ISSUE TITLE
How to upgrade polyphony

### ISSUE THREAD

**Issue by jjYBdx4IL** [asb2m10/dexed#327]
The mentioned preset has sound issues at high polyphony (> 16 ?), although CPU usage remains quite low.

Is there an easy way to increase the polyphony? Maybe through recompilation?

**Comment by asb2m10** [comment]
Yes, trough recompilation should be easy. Just change this : 

https://github.com/asb2m10/dexed/blob/8b5d92069a072802762b8182b44230401e531426/Source/PluginProcessor.h#L67
