### ISSUE TITLE
Can't load sysex banks into the plugin from Reaper

### ISSUE THREAD

**Issue by kara-louise** [asb2m10/dexed#328]
I used to be able to paste bank files either as SYSEX or MIDI files on to a track that had Dexed inserted, and pressing play would load it into the plugin. But nothing happens if I attempt this now.
I'm not sure if this is a problem with REAPER or Dexed, since other VSTS I have that except sysex banks such as PG-8x still work.
I've tried this with both the older vst 2 plugin and the current vst 3 build at time of writing.
I'm using version 6.51 of Reaper on Windows 10.
It would be a shame if this can't be addressed as currently this is the most accessible way of loading bank files I know of when using a screen reader.

**Comment by zloboslav** [comment]
I started Reaper "as administrator" and it started working again. After that I went to %APPDATA%\DigitalSuburban\Dexed and right clicked on properties of the "Cartridges" folder and I disabled the "read only" checkbox for all. That fixed it for me. This is my workaround, I hope it helps.

**Comment by asb2m10** [comment]
Older version of Reaper didn't stream any Sysex data ; but I've just tested this with the latest version of Reaper and Dexed and it works.

Should also applies to #401 

I will do a double check to see if there is no drawback before closing this issue.

**Comment by asb2m10** [comment]
I've bumped the JUCE version to 7.0.11 and now everything seems to work fine under Linux and OS X with the latest Reaper version. Please test the builds the related builds: https://github.com/asb2m10/dexed/actions/runs/10239126765
