### ISSUE TITLE
Build error on MACOSX Yosemite 10.10.3

### ISSUE THREAD

**Issue by atiq-cs** [asb2m10/dexed#33]
Hi,
I am interested in building the project in MAC OS X.

I have cloned the latest code from the repo. Opened project xcode and performed a build.

Following error came up,
failed to find AUResources/AUResources.r
/Users/musicapp/Code/dexed/JuceLibraryCode/modules/juce_audio_plugin_client/AU/juce_AU_Resources.r:49: ### /Applications/Xcode.app/Contents/Developer/usr/bin/Rez - SysError 0 during open of "AUResources.r".
Fatal Error!
/Users/musicapp/Code/dexed/JuceLibraryCode/modules/juce_audio_plugin_client/AU/juce_AU_Resources.r:49: ### /Applications/Xcode.app/Contents/Developer/usr/bin/Rez - Fatal Error, can't recover.
AUResources.r: ### /Applications/Xcode.app/Contents/Developer/usr/bin/Rez - Since errors occurred, /Users/musicapp/Library/Developer/Xcode/DerivedData/Dexed-evsgnqvxdyivzlasmaeyaglucqre/Build/Intermediates/Dexed.build/Debug/Dexed.build/ResourceManagerResources/Objects/juce_AU_Resources.rsrc's resource fork was not written.
Command /Applications/Xcode.app/Contents/Developer/usr/bin/Rez failed with exit code 3

Any suggestion/hint to resolve the issue is welcome.

**Comment by asb2m10** [comment]
You need to install AU support... see this : https://alexkenis.wordpress.com/2014/01/23/apples-audio-unit-examples-in-osx-10-9-and-xcode-5/
