### ISSUE TITLE
Dexed 0.9.0 fixed frequency displayed value is wrong

### ISSUE THREAD

**Issue by ShaydeNZ** [asb2m10/dexed#34]
I know the frequency Ratio display was fixed previously, but it seems the frequency Fixed display also needs correcting.  For instance, Coarse = 2, Fine = 34, produces 218.78 Hz according to osc_freq() in dx7note.cc, but the frequency displayed is 440 Hz in OperatorEditor::updateDisplay().

It appears to be the display that is wrong as listening to a 440 Hz fixed tone in Dexed, and comparing it to a known 440 Hz tone, they are clearly different.

**Comment by asb2m10** [comment]
Yes, the pitch is certainly not linear... now fixed in the 0.9.0 branch.

**Comment by ShaydeNZ** [comment]
Thanks, I can confirm the fix works for me.  Nice job on the plugin BTW.
