### ISSUE TITLE
Yamaha DX7IIFD w/ E! Grey Matter sysex loads as corrupted data in Dexed?

### ISSUE THREAD

**Issue by IDrinkLava** [asb2m10/dexed#350]
I tried to backup some files from my Yamaha DX7IIFD with MIDI-OX which I used to use all the time years ago. When I loaded the sysex into Dexed, it just shows up as completely corrupted data. When I send the sysex back to the DX7IIFD, it works perfectly fine. Here is [a test file](https://mega.nz/file/UHBTmQ7S#HnVqBKaFYIGYdR6hQmkM4q-_ulpRUqOoh8e8W8AHU3A) [should be MinoruMukaiya(KV03B).syx]

I'm assuming this problem might be because of the E! Grey Matter board installed on the hardware?

**Comment by asb2m10** [comment]
For now Dexed only works with the original Mark I cartridge, supporting the extended version means also supporting the storage which can be more tedious than expected.

If you need to work with those extended cartridges, you can use http://dxconvert.martintarenskeen.nl/ that can convert most of the DX familly cartridge to the DX7 Mark I.
