### ISSUE TITLE
JUCE Path error

### ISSUE THREAD

**Issue by Guest-1013** [asb2m10/dexed#351]
I'm using Windows 10. When I run the ./scripts/projuce.sh ,I was greeted by this:
`Generating build for VST3
Re-saving file: C:\Users\12012\Desktop\Music Softwares\Dexed\dexed-master\Dexed.jucer
Error when saving: At least one of your JUCE module paths is invalid!
Please ensure each module path points to the correct JUCE modules folder.`
I try to change the global path in JUCE GUI, but I don't know what to do with the "user module" path.
Could you please tell me how to fix it?

**Comment by asb2m10** [comment]
This error is caused by a local projucer configuration in the home directory. If you use cmake, you will not need the script to build the solution. The scripts are now deprecated since cmake will be used instead.
