### ISSUE TITLE
UI size is off after closing param dialog

### ISSUE THREAD

**Issue by falkTX** [asb2m10/dexed#36]
The setSize arguments on the PluginEditor constructor vs after closing param dialog are different.
I think you updated the code in one place and forgot to change where it was duplicated.

See https://github.com/DISTRHO/DISTRHO-Ports/commit/81cfcae381841917863ace9ddeeaacc98b0bdf77 for possible fix.

**Comment by asb2m10** [comment]
:D Fix is now committed on branch work-0.9.1. Thanks.
