### ISSUE TITLE
Complete instrument package and Midi instructions are supported.

### ISSUE THREAD

**Issue by ADG664** [asb2m10/dexed#361]
Will the future support:
1.high fidelity emulation, with choice of compromise level (good fidelity/fast, excellent fidelity/slow)
2.synthesis of melodic and percussive instruments
3.extensible polyphony
4.bundled collection of instruments
5.support for dynamic parameterization and automation
6.rigorous implementation of the MIDI standard
7.multi-channel operation with General MIDI compatibility
8.ability to synthesize entire MIDI files out of the box

**Comment by asb2m10** [comment]
Sorry but this is out of scope requirements for this project.
