### ISSUE TITLE
Dexed AU crashes Renoise on exit

### ISSUE THREAD

**Issue by boonier** [asb2m10/dexed#362]
Renoise v3.4.2
Monterey v12.6
Dexed AU v0.9.6

Create a new song
Add AU version of Dexed
Save...
Either exit Renoise, or create another new song (both cause a crash/freeze)

**VST3 version does not crash Renoise. Haven't checked VST**

The results from the console Renoise.log:

```
Application: Enter MainLoop...

AU: Trying to open plugin:'Digital Suburban: Dexed' (aumu:Dexd:DGSB)...
AU: Setup I/O...
AU: Plugin suggests routing: 0 inputs, 2 outputs
AU: Plugin accepted routing: 0 inputs, 2 outputs
AU: Inputs: 0 (max:0)  Outputs: 2 (max:2) in 0/1 busses
AU: Audio Unit has 1 MIDI output port(s)
AU: Setup Rate/Blocksize...
AU: Initializing...
AU: Setup Parameters and Presets...
AU: Start running...
AU: Instantiate OK
AU: Opening editor window for plugin 'Digital Suburban: Dexed'...
AU: Found a custom cocoa editor view component ('JUCE_AUCocoaViewClass_d80e4d3799d2c067')...

Application: Saving 'Dexed TEST.xrns'...
Application: 'Dexed TEST.xrns' was successfully saved.

AU: Editor window for plug 'Digital Suburban: Dexed' was closed

Application: Exit...

CrashLog: Caught signal: SIGABRT (6) ...

AU: Caught exception in AURender

Shut down: Stopped the Player

MIDI: Shut down: Closing all acquired MIDI devices...
```

**Comment by asb2m10** [comment]
Please test the nightly with this, I know that I've fixed a rare window close issue: https://github.com/asb2m10/dexed/releases/tag/NIGHTLY

**Comment by boonier** [comment]
Just installed the latest nightly; after some code signing issues, the AU version loaded fine, and also unloaded without the crash.

VST3 version seem to have issues with loading though, but that might be unrelated to this issue.

Tested on Renoise and Reaper

Cheers

**Comment by asb2m10** [comment]
Just tested this with Renoise 3.4.4 and latest Dexed build and everything is now working.
