### ISSUE TITLE
Dexed checkboxes are incorrectly represented as radio buttons

### ISSUE THREAD

**Issue by SeanLuke** [asb2m10/dexed#365]
Dexed has green radio buttons, rather than checkboxes, for its "Active output channels", "Active Input channels", and "Active MIDI inputs" selectors, even though they act like checkboxes. This caused a lot of grief for me as I selected a new Active MIDI input, unaware that the other input had not been deselected as would be expected in a normal radio button.  Please change these to checkboxes.

While we're at it, why are there more than one active MIDI Inputs?  Dexed still doesn't support sysex patch requests.

While we're at it, why is the MIDI Output a popup menu but the other choosers are checkboxes masquerading as radio buttons?

**Comment by probonopd** [comment]
> Dexed still doesn't support sysex patch requests.

It does in the latest build from https://github.com/asb2m10/dexed/actions/runs/10239126765.

**Comment by asb2m10** [comment]
Those checkbox are a relic from JUCE 3 look and feel. This has been upgraded to the latest that are more "checkbox" like.
