### ISSUE TITLE
Level scaling 'L/R curve' menus display only once

### ISSUE THREAD

**Issue by falkTX** [asb2m10/dexed#37]
This has been reported to me a few days ago, at https://github.com/DISTRHO/DISTRHO-Ports/issues/8
I don't know if it's a linux specific bug or not.

In any case I fixed it by calling the menu async. I based my code on the juce ComboBox showPopup.
(See the bug report for a fix)

**Comment by asb2m10** [comment]
I did had that issue on Linux but hated the "synchronous" popup hack that I've made. 

This is way more clean. Fix is now committed on branch work-0.9.1. :+1:
