### ISSUE TITLE
CLAP version does not work in Bitwig on M2 (Monterey)

### ISSUE THREAD

**Issue by TjShredder** [asb2m10/dexed#372]
The Clap version (0.9.7 nightly) is listed in the Plug-in error list with this:

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Error establishing metadata connection for command /usr/bin/arch -x86_64 "/Applications/Bitwig Studio.app/Contents/MacOS/Bitwig Plug-in Host X64-SSE41.app/Contents/MacOS/BitwigPluginHost-X64-SSE41" metadata 1234 5 2
exit code:1
stderr:
arch: posix_spawnp: /Applications/Bitwig Studio.app/Contents/MacOS/Bitwig Plug-in Host X64-SSE41.app/Contents/MacOS/BitwigPluginHost-X64-SSE41: Bad CPU type in executable

Bitwig should load the Intel version if there is no native version. But there should be a native version shouldn't it?

**Comment by asb2m10** [comment]
There is a good chance that the scanning didn't work because the app wasn't notarized. Please test new version:

https://github.com/asb2m10/dexed/releases/tag/v0.9.7pre4
