### ISSUE TITLE
cannot build Projucer > Xcode 'clap-juce-extensions/clap-juce-extensions.h' file not found

### ISSUE THREAD

**Issue by dataexcess** [asb2m10/dexed#373]
Hello there!

I can't wait to build this locally, but I'm stuck on the error 
`'clap-juce-extensions/clap-juce-extensions.h' file not found`

I tried adding the following paths to header search paths (both in projucer and in xcode) but to no avail:
```
/Users/Me/Projects/dexed/libs/clap-juce-extensions/include/clap-juce-extensions
/Users/Me/Projects/dexed/libs/clap-juce-extensions/include/clap-juce-extensions/*
```

Any idea how to fix this? thank you!

**Comment by dataexcess** [comment]
I ran the install instructions again and i noticed I could not finish the installation.
when executing the last "cmake --build ." command, the installation quits at the following: 

I'm on a intell apple, macos 12. 

```
[ 69%] Building CXX object Source/CMakeFiles/Dexed_Standalone.dir/__/libs/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.o
[ 70%] Building CXX object Source/CMakeFiles/Dexed_Standalone.dir/__/libs/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.o
[ 71%] Building CXX object Source/CMakeFiles/Dexed_Standalone.dir/__/libs/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.o
make[2]: *** No rule to make target `libs/clap-juce-extensions/libclap_juce_extensions.a', needed by `Source/Dexed_artefacts/Standalone/Dexed.app/Contents/MacOS/Dexed'.  Stop.
make[1]: *** [Source/CMakeFiles/Dexed_Standalone.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by mehdihajoub** [comment]
Hey @dataexcess, Same problem here, did you find any solution by then ?

**Comment by dataexcess** [comment]
Nope and I stopped trying .. :/ :)

**Comment by mehdihajoub** [comment]
I tried adding the files the linker was looking for in the place they should be according to the different headers. It just leads to an infinite loop of inclusion, it's like the clap submodule that we're supposed to install doesn't suit the version of dexed that is in the master branch :(

Did you find any alternative ?

Thanks for your answer :)

**Comment by asb2m10** [comment]
This means that not all submodules are pulled from github.

Use this to clone the repo: `git clone --recurse-submodules -j8 https://github.com/asb2m10/dexed.git`
