### ISSUE TITLE
The Dexed is loses the path to the active preset

### ISSUE THREAD

**Issue by hpr895** [asb2m10/dexed#374]
1. Open any preset by "CART" button, like "/Atari/7V5.SYX"
2. Select any preset, like "BELLS"
3. Click on the "CLOSE" button (optional)
4. Close the Dexed VST window
5. Open Dexed instance window again
6. Click in "CART" again
7. There is no way to recognize the active cartridge preset path or name

**Comment by probonopd** [comment]
In some DAWs it might be working only with VST2 but not 3. At least worth a try.

**Comment by hpr895** [comment]
> 

No, did'n work on FL 20(

**Comment by asb2m10** [comment]
I will add full path of cartridge on next release of Dexed. Duplicated #379

**Comment by hpr895** [comment]
Thank you very much! But for Windows 7 users and old version (0.9.6) projects I have found a solution to simply search program by name in Sublime text. For anybody who needs help: https://github.com/asb2m10/dexed/issues/56#issuecomment-2283852282
