### ISSUE TITLE
Copying and pasting voices as strings containing hex data

### ISSUE THREAD

**Issue by probonopd** [asb2m10/dexed#378]
It would be nice if once could copy and paste strings containing hex data (`F0 43 ...`). This would be very useful for being able to exchange individual voices easily with other programs.

**Comment by probonopd** [comment]
Excellent, thank you very much @asb2m10

**Comment by probonopd** [comment]
Hello @asb2m10 how exactly is this supposed to work? I tried Ctrl-C in REAPER (there it copies the whole Dexed plugin instance because this is how REAPER behaves), but aso in the standalone Dexed.exe Ctrl-C does not seem to copy a text string to the clipboard.

Could a "copy to clipboard" menu option be added here

![image](https://github.com/user-attachments/assets/c9379ebc-2b28-4170-9751-0867b32ce707)

That would copy a text like `F0 ... F7` to the clipboard?

**Comment by asb2m10** [comment]
For now it only works on operator and operators EG by right clicking on the object. But it is planned to work globally where if you right click, it should offer to copy the "context" (operator/operator eg/ptich eg/global program) content on the clipboard.

The content should be hexvalues, with a description of the content on the next line... it is implemented here: 

https://github.com/asb2m10/dexed/blob/fe6efbce641a6e7befd4c2e26dbb4f11a0e5216f/Source/PluginData.h#L258
