### ISSUE TITLE
CartManager draws a black frame (shadow) on desktop when visible

### ISSUE THREAD

**Issue by falkTX** [asb2m10/dexed#38]
At least on Linux when dexed cart-manager is visible there's a black frame/shadow on the desktop.

This seems to be because you use a top-level window for cartmanager but add it as a child component of the plugin UI.
Turning the CartManager class into a simple Component makes the shadow go away.

See https://github.com/DISTRHO/DISTRHO-Ports/commit/53458838505efef91ed069d0a7d970b6b3588eba for a fix.

**Comment by asb2m10** [comment]
I had issues on OS X with older version of JUCE. Now that I have upgrade to 3.2 it works as a simple Component. This fix is now committed on branch work-0.9.1. Thanks.
