### ISSUE TITLE
License should be LGPL instead of GPL

### ISSUE THREAD

**Issue by smaybius** [asb2m10/dexed#383]
Because of its nature as a plugin which counts as a library, there are projects that will want to use dexed as part of their DX7-ish emulation, but differences in licenses would make it impossible to include dexed right away, because the said projects are licensed under licenses that don't allow GPLv3 software to be included. Permissive licenses like MIT and the first few BSDs allow inclusion in projects of any license. The LGPL does the same thing, but it's perfectly copyleft like regular GPL and unlike the permissive licenses.

**Comment by asb2m10** [comment]
The engine is already on BSD, the UI is on the GPL because of JUCE. There is no point to re-license it to the LGPL since it requires JUCE.

**Comment by smaybius** [comment]
Late, but maybe specify the licensing by changing the LICENSE.md to specify what code is under that BSD license and that the JUCE component is under the GPLv3? Famitracker does it too, by stating that the code is under various licenses and that the program itself is under GPLv3 if that one emulation core is included.
