### ISSUE TITLE
MacOS release installer mpkg throws critical errors in Suspicious Package

### ISSUE THREAD

**Issue by svdeblk** [asb2m10/dexed#386]
[ EDIT: i should probably mention my environment: 
mac mini m2 pro running ventura v13.3 ]

first off thank you so much for archiving and maintaining this project. this is one of my favorite vst synths and i was pretty bummed when i discovered it had gone cold for a while. 

i tried running the latest macos installer (dexed-0.9.6-macos), pulled from the Dexed site and the releases page (they appear to be mirrors). 

Suspicious Package throws 2 critical issues

	1. can't get list of files to be installed, since the component package "Standalone.pkg" is missing or corrupted

	2. Can't analyze payload, since the component package "Standalone.pkg" is missing or corrupted

both have sub flags of 

	- the file "Info.plist" couldn't be opened
	- the operation couldn't be completed. Not a directory.

 i inspected the mpkg contents and found the "distribution.dist" script file in ./Contents/

on line 32:
     <pkg-ref id="com.digitalsuburban.DexedStandalone" version="0.9.6" installKBytes="7334">file:./Contents/Packages/Standalone.pkg</pkg-ref>

additionally
./Contents/Packages contains the following 

      	AU.pkg
      	Standalone.pkg
      	VST3.pkg

 i am not familiar enough with metapackages to know if it's a pathing issue, or if it is somehow corrupted/damaged.

 i was able to extract and export the vst3 and app files manually without launcing the respective pkg files, and can confirm that the standalone seems to be working fine. 

![Screenshot 2023-05-11 at 12 40 25 PM](https://github.com/asb2m10/dexed/assets/67727284/5d72f673-b591-4d48-8860-21b7002ca989)

**Comment by asb2m10** [comment]
Dexed is now sign with a Apple Developer ID. Please test next release :

https://github.com/asb2m10/dexed/releases/tag/v0.9.7pre4
