### ISSUE TITLE
Operator on/off button setting isn't stored

### ISSUE THREAD

**Issue by beeltink** [asb2m10/dexed#393]
When you

- turn off an operator
- store the patch
- re-open the patch

the operator is on again, but the level is set to 0

This is in 0.9.6. for Windows.

**Comment by BobanSpasic** [comment]
The original DX7 has the same behavior - operator on/off is not saved as part of the voice data.

**Comment by asb2m10** [comment]
As @BobanSpasic stated, the operator on/off is not saved on the original DX7, it replicates the DX7 behaviour.

I will add this case on the Dexed FAQ since it is a common question.
