### ISSUE TITLE
"Send current program to DX7" Does not send pitch EG data.

### ISSUE THREAD

**Issue by chrismitchrocks** [asb2m10/dexed#40]
When sending the current patch to the DX7, the Pitch EG data (levels and rates) is not transmitted.

It does send correctly if the entire patch bank is submitted.

I don't know if this is something that is impossible to do or a bug, just listing it as a known issue.

**Comment by asb2m10** [comment]
looking at the code there might be a bug : the sysex length of a single pgm seems way too short. will test this in the coming week.

**Comment by asb2m10** [comment]
Just did a test on my side with the "Send current program to DX7" and pitch EG data changes works.

There was a bug if you used "send program" from the CART dialog and I've just fixed this with the 0.9.1 branch.

Does your issue occurs on the main Dexed window or with the "CART" dialog ?

**Comment by chrismitchrocks** [comment]
This occurred on the main Dexed window, when right clicking and sending to DX7.

**Comment by asb2m10** [comment]
Closing this since no user feedback.
