### ISSUE TITLE
Expose .syx files as JSON or vstpreset?

### ISSUE THREAD

**Issue by turian** [asb2m10/dexed#400]
There are many .syx files floating around, but the file format is hard to understand. It would be amazing if the presets were human-readable.

There is a lot of work on inverse synthesis (pick paramaters given a sound) using Dexed, and it would be amazing to be able to easily have a corpus of *good* presets. However, I am tearing my hair out trying to parse the .syx file format. And generating random patches isn't cool.

I would love a syx_to_json script, that would be amazing.

**Comment by asb2m10** [comment]
I get the idea but I think this is out of scope for this project. Please see Martin Python scripts for reading DX sysex : https://dxconvert.martintarenskeen.nl/ ; you should have the building blocks for this.
