### ISSUE TITLE
DEXED PATCH VOLUME GETS QUIETER AS YOU MOVE UP IN PITCH

### ISSUE THREAD

**Issue by JARRODMUSIC** [asb2m10/dexed#406]
HI. Relatively new to FM synthesis so this might be a very simple fix. 

I have a patch that gets quieter as you move up the keyboard.

![Image](https://github.com/asb2m10/dexed/assets/156097047/d1a97009-692e-4eaa-b5d2-3ece3fa0546a)

Can anyone point me in the right direction?

Thanks

**Comment by scratch-nakashima** [comment]
You will need to increase the value of the knob marked "cutoff," which is located in the lower left corner. At the same time, the tone will change, but the higher notes should come out. With this setting, the higher frequencies are cut off. (I am using a translator, so the translation could be wrong)
![Cutoff](https://github.com/asb2m10/dexed/assets/161414629/e60bd44a-eb92-41df-a820-4c27d759c2ff)

**Comment by asb2m10** [comment]
@scratch-nakashima is probably right, unless you can share the Logic project, this is the best we can do.
