### ISSUE TITLE
Automated parameters not updated in UI (VST3)

### ISSUE THREAD

**Issue by Spacechild1** [asb2m10/dexed#407]
The VST3 version of Dexed does not update parameters in the UI when I try to automate them programatically, e.g. with automation curves in Reaper or with messages in Pure Data (see https://git.iem.at/pd/vstplugin). The corresponding UI elements just don't move. Curiously, a few parameters do work, e.g. `Resonance`, `Cutoff`, `OP4 L SCALE DEPTH` or `OP4 BREAK POINT`.

Tested with Dexed 0.9.6 (VST3) on Windows 10.

**Comment by asb2m10** [comment]
There are known issues with VST3 automation with 0.9.6. Please confirm if the issue is still present with the pre-release version.

https://github.com/asb2m10/dexed/releases/tag/v0.9.7pre4
