### ISSUE TITLE
Broken link on GitHub Pages for Dexed_cart_1.0.zip (http instead of https)

### ISSUE THREAD

**Issue by Pete-Lawrence** [asb2m10/dexed#421]
https://asb2m10.github.io/dexed/

Broken link on GitHub Pages for 'Dexed_cart_1.0.zip'.
The link doesn't work because it links to http instead of https, easy fix.

The incorrect current link.
http://hsjp.eu/downloads/Dexed/Dexed_cart_1.0.zip

The easy fix.
https://hsjp.eu/downloads/Dexed/Dexed_cart_1.0.zip

**Comment by asb2m10** [comment]
Fixed ; thanks for reporting
