### ISSUE TITLE
Mac (arm) .mpkg "file is damaged"

### ISSUE THREAD

**Issue by tezza1971** [asb2m10/dexed#422]
just tried installing 0.9.6 and after several attempts at downloading the zip file and runing the resulting .mpkg file, I got the following error.

<img width="265" alt="image" src="https://github.com/asb2m10/dexed/assets/5106858/fbb4b23c-24fe-4af6-b78b-1cfaf69e75eb">

I'm running Sonoma 14.4.1 on an M1 mac mini.

I tried a pkgutil --expand -v and it just came back with "Could not open package for expansion:"

Upon further prodding from the command line, I found I could CD into the .mpkg to find the AU.pkg and expand that to rename the payload file to Dexed.component and copy it into /Library/Audio/Plugins/Components

But I'm sure this is not the intended process to have Dexed installed.

**Comment by asb2m10** [comment]
Hi, this is because I didn't built Dexed package with a valid "Apple Developer ID", this is how [gatekeeper](https://en.wikipedia.org/wiki/Gatekeeper_(macOS)) works. I'm in the process to buy a "Apple Developer ID" for the next version.
