### ISSUE TITLE
vst/component for mac has incorrect version - 1.0.0

### ISSUE THREAD

**Issue by syabro** [asb2m10/dexed#428]
<img width="280" alt="image" src="https://github.com/asb2m10/dexed/assets/29029/6dc0746a-6e0c-4918-a9be-9ae4819a3bb1">

but it's 0.9.6 :(

**Comment by asb2m10** [comment]
We have to continue using 1.0.0 as component versions until we reach the real "1.0.0" version, otherwise the DAW will think the 2 versions are incompatible.

Once we hit 1.0.0, the component and dexed version will always match

**Comment by syabro** [comment]
@asb2m10 I'm working on VST markteplace http://presync.io and now trying to add update mechanism. 
How can I track the real version now?

**Comment by asb2m10** [comment]
github releases are the reference: https://github.com/asb2m10/dexed/releases

**Comment by syabro** [comment]
@asb2m10 emm, I mean I've to check user installed version :(

**Comment by asb2m10** [comment]
Sadly your best bet is md5sum based on the binaries for the officials builds. :/
