### ISSUE TITLE
Compiled versions for Linux users

### ISSUE THREAD

**Issue by marko-lazic** [asb2m10/dexed#43]
Hey there,

I use Fedora and i tried to compile dexed so i can try it out but i must say it is big pain to do and in the end i failed.

Some packages i had to: sudo dnf install libXcursor-devel libXinerama-devel freetype-devel libX11-devel alsa-lib-devel

But in the end i got stuck on this:
 #include <public.sdk/source/vst2.x/audioeffectx.h>

It asks for something that is forbidden in free software community, the proprietary vst2.x libraries.

Could someone just build .so libraries for us, the linux users or help me to figure out this barrier?

**Comment by asb2m10** [comment]
Hi, 

You can find the Linux binaries here : http://distrho.sourceforge.net/ports

I'm strongly suggesting to follow this project that has also great plugins for Linux (including Dexed): https://github.com/DISTRHO/DISTRHO-Ports 

There, you will have specific information about building Dexed without the proprietary vst2.x libraries.

**Comment by marko-lazic** [comment]
Thanks asb3m10 for these links.
