### ISSUE TITLE
Return of reference to stack variable

### ISSUE THREAD

**Issue by JDCodeIt** [asb2m10/dexed#44]
I noticed while compiling under Linux, there was a warning about this function returning a stack variable, which of course may not exist when the caller goes to look for it. You might consider making this "static" so it is on the heap instead.

```c++
Image &findImage(String path) {
    Image img;
    // change the above to static Image img;

    if ( path.length() <= 3 ) 
        return img;
    File imgFile(path);
    img = ImageCache::getFromFile(imgFile);
    return img;
}
```

**Comment by asb2m10** [comment]
ImageCache was already returning a static reference; the problem was the & on the return type;;; my bad, thanks for reporting.
