### ISSUE TITLE
Installer does not support Apple Silicon

### ISSUE THREAD

**Issue by ARCHVILE-DRS** [asb2m10/dexed#445]
Read through some past issues and tested v0.9.7. I'm prompted to install Rosetta upon opening the installer, so I guess the installer doesn't support Apple Silicon yet.

**Comment by Casuallynoted** [comment]
Also noticing this. Curious if the plugin will be updated to run on Apple Silicon.

**Comment by asb2m10** [comment]
The plugin runs on Apple Silicon, it's the Apple installer that is based on x64; for now test this with the latest signed pre release: https://github.com/asb2m10/dexed/releases/download/v0.9.8pre1/dexed-macos-0.9.8pre1.zip

**Comment by Casuallynoted** [comment]
Thank you so much!
