### ISSUE TITLE
Rejected Audio Units Components (the code is valid but does not seem to be an app)

### ISSUE THREAD

**Issue by nicdve** [asb2m10/dexed#447]
I downloaded Dexed and found out that it not passed the Logic Pro validation, so Dexed is not appearing in the plugin section.

I test it with $ spctl -a -t exec -vv Dexed.component , and it seems my mac sees it not to be an app.

Here is the result :
Dexed.component: rejected (the code is valid but does not seem to be an app)
origin=Developer ID Application: Pascal Gauthier (PZ6T894W8E)

The standalone app work fine, just the Audio Units in Logic Pro that cannot open Dexed.

Here is my system : 
MacBook Pro 15 Inch 2017, Intel i7 3.1 GHz Quad-Core
Mac OS Ventura 13.4
Logic Pro 10.7.8
Dexed 0.9.7

Anyone knows what happened ?

Thanks!

**Comment by asb2m10** [comment]
Duplicate #451
