### ISSUE TITLE
Dexed 0.9.7. AU does not work in Logic Pro 11 - validation failed

### ISSUE THREAD

**Issue by fvv1** [asb2m10/dexed#451]
Dexed 0.9.7. Audio Unit cannot be used in Logic Pro - validation failed

Newest Version used of Logic:
Logic 11.0.1
Build Version 6029

Following error occurs:

validating Audio Unit Dexed by Digital Suburban:

    AU Validation Tool
    Version: 1.10.0 
    Copyright 2003-2019, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aumu' - 'Dexd' - 'DGSB'
--------------------------------------------------
Manufacturer String: Digital Suburban
AudioUnit Name: Dexed
Component Version: 1.0.0 (0x10000)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
Time to open AudioUnit:         569.892 ms
WARM:
Time to open AudioUnit:         1.046  ms
This AudioUnit is a version 2 implementation.
FIRST TIME:
Time for initialization:        0.036 ms

* * PASS
--------------------------------------------------
VERIFYING DEFAULT SCOPE FORMATS:
Input Scope Bus Configuration:
 Default Bus Count:0

Output Scope Bus Configuration:
 Default Bus Count:1
    Bus Name: output
    Default Format: AudioStreamBasicDescription:  2 ch,  44100 Hz, Float32, deinterleaved
    Has Channel Layouts: 0x640001 0x650002 0x660002 0x670002 0x6A0002 
    Default Layout:
	Tag=0x650002, Num Chan Descs=0

* * PASS
--------------------------------------------------
VERIFYING REQUIRED PROPERTIES:

* * PASS
--------------------------------------------------
VERIFYING RECOMMENDED PROPERTIES:
  VERIFYING PROPERTY: Latency
    PASS

* * PASS
--------------------------------------------------
VERIFYING OPTIONAL PROPERTIES:
  VERIFYING PROPERTY: Tail Time
    PASS
  VERIFYING PROPERTY: Bypass Effect
    PASS

* * PASS
--------------------------------------------------
VERIFYING SPECIAL PROPERTIES:

VERIFYING CUSTOM UI
Cocoa Views Available: 1
  JUCE_AUCocoaViewClass_c7890cad9bf351fd
    PASS

DEFAULT PRESET: 0, Name: Say Again.

HAS FACTORY PRESETS

VERIFYING CLASS INFO
    PASS

TESTING HOST CALLBACKS
    PASS

* * PASS
--------------------------------------------------
PUBLISHED PARAMETER INFO:

# # # 155 Global Scope Parameters:
WARNING: retrievedValue = 0.999939 (was 1.000000), Parameter did not retain maximum value when set

* * PASS
--------------------------------------------------
FORMAT TESTS:

Reported Channel Capabilities (explicit):
      [0, 1]  [0, 2]  

No Input, Output Chans:
0-1   0-2   0-4   0-5   0-6   0-7   0-8
X     X                                   

# # AudioChannelLayouts (5), Output Scope:
ChannelLayout is Writable: T
The Unit publishes the following Channel Layouts:
  0x640001, 0x650002, 0x660002, 0x670002, 0x6A0002, 

Is Audio Channel Layout Available:
Mono    Stereo  Binau.  AU_4    Ambi.   AU_5    AU_5_0  AU_6    AU_6_0  AU_7_0  AU_7_0F AU_8    AU_5_1  AU_6_1  AU_7_1  AU_7_1F 
X       X       X                                                                                                               

Current Format:AudioStreamBasicDescription:  2 ch,  44100 Hz, Float32, deinterleaved
Current Format Tag = 0x650002, New Format Tag = 0x640001, Success - did not reset format with mis-matched layout

Current Format:AudioStreamBasicDescription:  2 ch,  44100 Hz, Float32, deinterleaved
Current Format Tag = 0x650002, New Format Tag = 0x650002, Successsful

Current Format:AudioStreamBasicDescription:  2 ch,  44100 Hz, Float32, deinterleaved
Current Format Tag = 0x650002, New Format Tag = 0x6A0002, Successsful

* * PASS
--------------------------------------------------
RENDER TESTS:

Output Format: AudioStreamBasicDescription:  2 ch,  44100 Hz, Float32, deinterleaved
Render Test at 512 frames
Slicing Render Test at 64 frames
  PASS

Render Test at 64 frames, sample rate: 22050 Hz
Render Test at 137 frames, sample rate: 96000 Hz
Render Test at 4096 frames, sample rate: 48000 Hz
Render Test at 4096 frames, sample rate: 192000 Hz
Render Test at 4096 frames, sample rate: 11025 Hz
Render Test at 512 frames, sample rate: 44100 Hz
  PASS

1 Channel Test:
Render Test at 512 frames

validation result: Validierung fehlgeschlagen

**Comment by fvv1** [comment]
Update: I have found out that this issue doesn't occur on version 0.9.6 from 2021 - the installation of version 0.9.6 has been done successfully

**Comment by asb2m10** [comment]
This is a know issue with 0.9.7 and AU validation ; please use the latest build: https://github.com/asb2m10/dexed/actions/runs/10239126765

**Comment by Zuekiin** [comment]
> This is a know issue with 0.9.7 and AU validation ; please use the latest build: https://github.com/asb2m10/dexed/actions/runs/10239126765

Sorry for being a noob but I have the same issue. Where on the link you pointed to do I find the build to download?

**Comment by asb2m10** [comment]
Please test this with the latest signed released: https://github.com/asb2m10/dexed/releases/download/v0.9.8pre1/dexed-macos-0.9.8pre1.zip

**Comment by aestuar** [comment]
@asb2m10  it works! thanks!
