### ISSUE TITLE
Instruments change whenever playback controls are used in Logic Pro

### ISSUE THREAD

**Issue by Casuallynoted** [asb2m10/dexed#453]
At the moment, when using Dexed on Logic Pro, I can set the instruments whatever way I want - but then when I hit play or go to beginning, the instruments change- usually to the first or last in the cart. Running on the latest Logic Pro X on Apple Silicon (built from source)

**Comment by asb2m10** [comment]
Can you provide a Logic project that I can fully reproduce this ? I cannot see this on my side.

**Comment by Casuallynoted** [comment]
Absolutely, and I took a screen recording.

https://github.com/user-attachments/assets/d55301dd-cda4-4f63-8d2f-99ea824f7b7a

https://xdda.casually.cat/s/qB96ECzZFeye8Ne

**Comment by asb2m10** [comment]
You midi track has a Program Change automation that is set to 32. Remove this and you will have the expected behaviour.
