### ISSUE TITLE
app contains version number 1.0.0 instead of 0.9.8 

### ISSUE THREAD

**Issue by suschizu** [asb2m10/dexed#454]
the info.plist shortVersionString and BundleVersion strings never change - they always stays on 1.0.0 
the info.plist should contain the correct version notation:

<img width="408" alt="Screenshot 2024-10-09 at 23 06 39" src="https://github.com/user-attachments/assets/b95fdd5a-2715-42b2-95ec-a3a6a812e035">

<img width="465" alt="Screenshot 2024-10-09 at 23 07 43" src="https://github.com/user-attachments/assets/d417c45c-f8a9-4df1-959e-2b97a11bfcd7">

**Comment by asb2m10** [comment]
Cannot downgrade the version, it will break compatibility in DAW format detection. This will be in sync when 1.0.0 version will be release and updated afterwards.
