### ISSUE TITLE
Send Program ' 'to DX7 is sending 161 byes to my TX-7

### ISSUE THREAD

**Issue by waltercruz** [asb2m10/dexed#46]
And doesn't work, cause a DX7 single patch should be 163 bytes. There's soewthing wrong in my setup maybe? Or it's a bug on dexed?

**Comment by waltercruz** [comment]
Ok, 'send current program' works, but 'send program' in the cartdrige, don't

**Comment by asb2m10** [comment]
This was a known issue and it is already fixed in the 0.9.1 branch. I'll close this issue when 0.9.1 beta builds (end of december) will be available.
