### ISSUE TITLE
Diagonal modulation paths missing from algorithm diagrams

### ISSUE THREAD

**Issue by juhu7** [asb2m10/dexed#47]
Consider the algorithm diagram in DEXED's UI: algorithm 24 and algorithm 25 look exactly the same, whereas on the diagrams printed on top of a real DX7 they are obviously different from one another (as well as different from what DEXED is showing). Looks like diagonal modulation paths are missing from DEXED's algorithm diagram display.

**Comment by asb2m10** [comment]
Yes it was missing. It is now added to the new 0.9.1 version. 
Thanks for reporting.
