### ISSUE TITLE
Preset loading improvements

### ISSUE THREAD

**Issue by mkruselj** [asb2m10/dexed#49]
* Please add an option for single-click loading in preset manager as opposed to double-click loading

* Add previous-next buttons for preset loading next to preset name/dropdown (to the left of STORE button).

**Comment by asb2m10** [comment]
I think there is missing space for the "previous-next" button; but I'm planning to implement the "single-click" in the 0.9.2 version

**Comment by mkruselj** [comment]
There's enough space if you do it like this: 

![dexedprevnext](https://cloud.githubusercontent.com/assets/2393720/12116711/1fa524c4-b3bc-11e5-889e-86f4cfb824ba.png)

Which I think is the most logical way of having it.

**Comment by mkruselj** [comment]
Any comments on the above suggestion, please? :)

**Comment by asb2m10** [comment]
It's doable... will add it to my 0.9.2 todo list.
