### ISSUE TITLE
Being able to change EG values (and operator level) in real time

### ISSUE THREAD

**Issue by alfonso73** [asb2m10/dexed#54]
Hi! Would be great to have VST automation for every parameter.
Any hope? thanks and great work here!!

**Comment by asb2m10** [comment]
Hi, all of the parameters stored in a program are available via VST automation. Which vst automation is not working ?

**Comment by alfonso73** [comment]
Hi Pascal,
thanks for the reply. sorry you're right.
But the thing is that i.e, the Level parameter is not changed when the
notes are playing, it only changes when a new note is triggered this makes
impossible to do FM "filtering" effects. I use do have a DX7 in the '80s
and really i don't remember if via SysEx this was possible.
Anyway this would be a "modern" feature wich not interfer with the
emulation principle.
As far as i can se this is true for every parameter.
While it is normal for the EG related parameters this is not good for
things like Operator Level and Pitch and Filter Cutoff (cutoff was not in
original DX7 too )
I think that the Coarse parameter should be interpolated because it has a
lot of zipper noise.
btw congrats for this great project and let me know you opinions.
bests
a.

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by alfonso73** [comment]
Hi,
any opinion on the above topics?
thanks and all the best
a.

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by asb2m10** [comment]
The envelopes (and op volume) right now are not real-time since they would have to be recalculated llive and the way that I've did it before was not similar to what the DX7 does. When I do the envelopes refactoring, this will be addressed.

**Comment by alfonso73** [comment]
Hi Pascal, many thanks.
I really think that your nice work of art can gain more expressive power
with live updating of Operator Levels and Volume.
All the best!
a.

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by clayc54** [comment]
hi alfonso
check out this youtube using a dx7 to get filtering effect while holding keys down.
https://www.youtube.com/watch?v=ErfPxDp9Igo

instead of automating operator level, you use EG1 and assign mod wheel, or you could automate it?, then you can control the 'filter' effect with the mod wheel without having to retrigger a note.

i havent checked if this works with dexed but it does with an actual dx7 so you would expect that it does :)

hope this helps
