### ISSUE TITLE
Problem sending new sysex file to hardware DX7

### ISSUE THREAD

**Issue by ansorg02** [asb2m10/dexed#55]
I have no problem sending cartridge-information to my DX7, but when I assemble a cartridge with existing sounds (drag and drop in the cartridge view between two different sysex files) and then save that cartridge as a new sysex, the new sysex file can not be send to my DX7. When looking at the sysex code it differs at the beginning, in what I understand as the "model ID". Instead of 09 as in the preexisting cartridge it’s now 00, perhaps this is what's causing the problem?

Code from preexisting sysex: F0 43 00 09
Code from new sysex: F0 43 00 00

**Comment by asb2m10** [comment]
You are right, this is a bug, I didn't check that when I've refactored the code. 0.9.2 will be fix all of the sysex compatibility bugs.

**Comment by ansorg02** [comment]
That's good to hear! And thanks for a great program, it solves a lot of things for me!
