### ISSUE TITLE
"Midi Interface: Error Opening Midi Ports"

### ISSUE THREAD

**Issue by deadpahn** [asb2m10/dexed#57]
DAW: Renoise
INTERFACE: Native Instrument Komplete 6
SYNTH: Yamaha TX7

Won't let me connect to the device. Tried it in VST HOST but I still get the error.

**Comment by asb2m10** [comment]
This usually occurs on Windows when the midi port is used by another program (e.g. renoise in your case). On windows, some midi drivers doesn't support multiple program using the same midi port. 

Confirm that no other software is using the same midi device and test it again to see if you have the same issue.

**Comment by deadpahn** [comment]
I got it to work by using "savihost". Thanks !

**Comment by FutureRap** [comment]
You have to check if the MIDI is activated also in an oher track. I had the dexed activeded in track 1 and 4. And the track 4 had this error because you can not activate the midi in morenthen one track at the same time
