### ISSUE TITLE
Cartridge data not recognised from DX7s

### ISSUE THREAD

**Issue by Inspector42** [asb2m10/dexed#59]
I own a DX7s and when I transmit 32 voice data in block, there are obviously other SysEx messages send beforehand (e.g. microtune data), which didn´t exist in the original DX7 I believe.
Dexed 0.9.1installed as AU in Logic 10.2.2 running on 10.11.3 does not seem to receive the bulk data, also the indicator beside the MIDI-In Port in Dexed does only light up shortly while the DX7s continues to send data. The voice names in the cartridge pull-down do not change and I also cannot locate any file, that is created.
It seems the extra syses-messages are not properly ignored and prevent the reception of the voice data.
I can transmit single voice data without problem
If I remember correctly, this worked in 0.8.1.

**Comment by asb2m10** [comment]
I don't know if it work on 0.8.1 (don't think so), but I've already committed the fixes for this. 

In 0.9.2, you will be able to send any type of sysex file, as long as it contains 0xF0 ...
