### ISSUE TITLE
Dexed needs a DC filter on the output

### ISSUE THREAD

**Issue by MD-78** [asb2m10/dexed#61]
0.9.1 x64

Many patches ("BANKS, T." as good example) have pretty high content at 25 Hz. I don't think that this should be there. I think there should be a Highpass filter (at 10 Hz maybe) on the output.

![dc](https://cloud.githubusercontent.com/assets/17949026/13900661/757f27ee-ee0b-11e5-8fe2-31689a8bf1ad.jpg)

**Comment by asb2m10** [comment]
Humm.. maybe. Can I run DIGICheck without having a RME card ?

**Comment by MD-78** [comment]
No, it needs a RME card. Maybe you can test/see it with other VST analysers:

http://www.voxengo.com/product/anspec
http://www.voxengo.com/product/span

**Comment by MD-78** [comment]
0.9.2 still has this issue.

**Comment by asb2m10** [comment]
FM can generate a huge amount of low frequency (in the above screenshot is -40db for just >25Hz is impressive). 

Let's not forget that a DC filter is just a filter and going beyond (maybe) -5db, it will modify the audible range and I don't want that. I would be curious to see how the DX7 implements this.
