### ISSUE TITLE
LFO Delay bug

### ISSUE THREAD

**Issue by Sentinel77** [asb2m10/dexed#63]
Hi,  

There is a bug with the LFO Delay.
On certain delay values, once the lfo starts, it will suddenly stop, and the delay time will restart. Depending on the project sample rate and the delay value chosen, this will loop a number of times then continue normally, or loop non stop.

example:
- select INIT to create a new sound.
- turn up 'PMD'
- increase the 'LFO Delay' to one of the problem values shown below, eg. 85
  Notice the vibrato restarting.

Behaves differently depending on project sample rate.
48000 sample rate
the following delay values glitch:
74, 77, 79, 80, 82-99

44100 sample rate
the following delay values glitch:
85, 93

thanks.

Great vsti!

**Comment by MD-78** [comment]
Confirmed (0.9.1 x64).

**Comment by asb2m10** [comment]
Good catch (and documented issue). Will try to fix this in 0.9.2

**Comment by asb2m10** [comment]
The delay was not catch if it got beyond 32-bit... now fixed.

**Comment by Sentinel77** [comment]
Hi  @asb2m10 
This is working good now. 

Thank you.
