### ISSUE TITLE
Preset loading bug

### ISSUE THREAD

**Issue by Sentinel77** [asb2m10/dexed#64]
Hi,

 I noticed a bug with loading presets from the 'CART' window, right side list.

If the patch is selected from the lower 'currently loaded cartridge' window it loads correctly.
But if the patch is selected from the 32 patches on the right hand side, then the following four parameters will not be loaded: 
wave, speed, delay, LFO key sync    (although visually on the main window it appears as if they were loaded)
Instead those four parameters already loaded from a prior patch are used.

example using the default Dexed_01 patches:
- from the 'CART' window, double click the patch 'LFORez ++Y' from the lower window of patches.
- then from the right hand list select 'SAW EM UP'
-  'SAW EM UP' patch will sound different than usual as it is using four of the parameters from the previous patch.
- now select 'SAW EM UP' from the lower window and hear the normal sound of this patch.

The right side patches should load all parameters as the lower window of patches does.

thanks.

**Comment by asb2m10** [comment]
Confirmed. Will try to fix this in 0.9.2

**Comment by Sentinel77** [comment]
This fixed the issue.  Thank you.
