### ISSUE TITLE
sysex patch install

### ISSUE THREAD

**Issue by ajkonn** [asb2m10/dexed#65]
Hi
Installed dexed as a logic pro x plugin, no probs...
also DL'd a bunch of sysex file patches.

I have no idea what to do with the files.
Help appreciated.

**Comment by Sentinel77** [comment]
Click on the 'CART' button, then click on 'SHOW DIR', it will show you where the cartridge folder is. Put your .syx files in that folder.  Then in the dexed 'CART' window you can right click and pick 'Refresh' and they will show up.

**Comment by asb2m10** [comment]
Thanks @Sentinel77 for the hint. 

Hope @ajkonn, that it answered your question.
