### ISSUE TITLE
Amplitude Modulation Depth effective range bug

### ISSUE THREAD

**Issue by Sentinel77** [asb2m10/dexed#67]
Hello,

  I noticed that the 'AMD' (Amplitude Modulation Depth) control, has a bug affecting the range of its control.  Instead of the control being effective from 0-99, only the values between 49-99 affect the amplitude modulation depth. Values from 0-49 have an amplitude modulation depth of zero.

 This bug seems related to the 'A mod sens' volume bug, in that both occur with a new instance of dexed, and both get corrected if you go to the 'PARM' window and hit 'OK', or if you touch your midi controllers modulation wheel.

example:
- open a New instance of dexed. (or reopen a project with dexed)
- hit 'INIT' to create a new sound.
- turn up 'A mod sens' on operator 1.
- turn up 'AMD' to 49.   Notice that there is unexpectedly no tremolo effect up to value 49.
- hit 'PARM' and press 'OK', Or make some movement on the modulation wheel of your midi controller.   Notice that a middle value of 49 now correctly has a noticeable tremolo, and the range of the 'AMD' control will now correctly be effective from 0-99.

Thanks.

**Comment by MD-78** [comment]
Confirmed (0.9.1 x64)

**Comment by Sentinel77** [comment]
Hi  @asb2m10 

  I see two issues causing this bug and the related  ['A mod sens' volume bug](https://github.com/asb2m10/dexed/issues/66)

Here is a fix for EG Bias that will correct some of the strange AMD behaviour noted above:
https://github.com/Sentinel77/dexed/commit/5c9b2a4ea2b59e68d4afcdd57a9a95cf069b28a7


But the second issue that still needs to be fixed is that dexed is always starting with EG BIAS  on, even when dexed has it turned off in the PARM window.  Some patches can sound very different when this is unexpectedly on.

It will be good if dexed can be made to check for our EG BIAS setting at startup.  


Thanks.

**Comment by asb2m10** [comment]
Hi @Sentinel77 , thanks for your contribution... I will merge those into the new version and make the proper credits. I'm very busy right now but will have some time in the end of December to make a 0.9.3 version with the required fixes.

**Comment by Sentinel77** [comment]
This is working in 0.9.3
thanks.
