### ISSUE TITLE
Loading SysEx file fails if if channel byte is not 0x00  

### ISSUE THREAD

**Issue by mtarenskeen** [asb2m10/dexed#70]
I have noticed that Dexed cannot load a DX7 sysex file correctly if the third byte does not equal 0x00.
The third byte in a DX7 sysex bankfile can be anything between 0x00 (channel=1) and 0x0f (channel=16). In the DX7/TX7 SysEx specification this is described as follows:

Status = 11110000
ID = 01000011
Sub Status/Ch. = 0000nnnn

Dexed fails if nnnn is anything other than 0000. This should be fixed.

Also, patchloading could be more flexible if Dexed would NOT assume a file to have a size of 4104 bytes, but instead would iterate through the values of the bytes and search for the Yamaha DX7 header bytes. From there it should test if the 4104th byte equals 0xf7. This way much more DX7 patches, including those with additional headers, DX7II files, TX7 files with performance data, would be imported correctly. Just a thought, nothing urgent: DXconvert from http://dxconvert.martintarenskeen.nl can convert almost anything (including 4-op FM synth patches) to a DX7 format that Dexed can read.

**Comment by asb2m10** [comment]
Hi,

Those fixes are already in the branch work-0.9.2 (#59); including the sysex streaming. It's just that I've have to find time to finish what I've already planned for this release.

**Comment by mtarenskeen** [comment]
OK, thanks. No need to hurry.

 

Van: Pascal Gauthier [mailto:notifications@github.com] 
Verzonden: maandag 13 juni 2016 19:35
Aan: asb2m10/dexed <dexed@noreply.github.com>
CC: Martin Tarenskeen <m.tarenskeen@zonnet.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [asb2m10/dexed] Loading SysEx file fails if if channel byte is not 0x00 (#70)

 

Hi,

Those fixes are already in the branch work-0.9.2 (#59 <https://github.com/asb2m10/dexed/issues/59> ); including the sysex streaming. It's just that I've have to find time to finish what I've already planned for this release.
