### ISSUE TITLE
Always crashes when changing preset in LMMS 1.1.3

### ISSUE THREAD

**Issue by soppe23** [asb2m10/dexed#73]
Every time I change preset from the default preset LMMS 1.1.3 crashes and sometimes Dexed goes all black. I have 64-bit system but also tried 32-bit Dexed and it crashed also.
Only other patch I can select without crash is init patch.

**Comment by asb2m10** [comment]
Did you build it yourself or used an external package ? I've never used LMMS....

**Comment by soppe23** [comment]
You mean presets? I used presets which came with Dexed.
I also experienced crash with Helm, so I think the crash is caused by LMMS, not Dexed.
