### ISSUE TITLE
Microtonality support

### ISSUE THREAD

**Issue by suhr** [asb2m10/dexed#74]
See [MIDI Tuning Standard](http://www.microtonal-synthesis.com/MIDItuning.html) and [Scala file format](http://www.huygens-fokker.org/scala/scl_format.html).

Additional info: [31ET](http://31et.com/) is [fun](http://tinyurl.com/zwf4jm5).

**Comment by Iu-Gob** [comment]
+1. Regards

**Comment by SeanArchibald** [comment]
If microtonal tuning support was added to Dexed it really would be a dream come true.

**Comment by asb2m10** [comment]
Microtonality is now supported.
