### ISSUE TITLE
Trying to get a 10.6.8 friendly version

### ISSUE THREAD

**Issue by Eamoex** [asb2m10/dexed#76]
Hi, first, thanks for this great project. I have both a DX7 and a Volca FM, so your great piece of software is the missing link... but my computer is old (MacBook Core2 Duo running 10.6.8). I've tried to load the plugin in every possible free host available but it never ever appears in the lists. When the host lets me select it directly from a dialog, it creates an error.

I've found versions 0.9.1 and 0.8.0. Maybe an even lower version could start?

**Comment by asb2m10** [comment]
You can try the latest version that supported OS X 10.6 : it's Dexed 0.9.0 : http://le-son666.com/software/dexed/dexed-0.9.0-osx.zip

Let me know if this works... and sorry for not supporting anything less than 10.7; Apple really does everything they can to break compatibility between XCode SDKs.

**Comment by Eamoex** [comment]
Great, thanks very much for the link! It does work. Thanks for the great 
software!

Using Dexed in conjunction with Korg's Volca FM is a real pleasure. In 
case you're interested and for your reference, we're having a good 
discussion about SysEx out of and into Dexed with the Volca FM here on 
Korg's forums 
<http://www.korgforums.com/forum/phpbb2/viewtopic.php?t=106026&sid=7593053c43f7879d98c4f29e62236580>.

Have a good day
Cheers

**Comment by asb2m10** [comment]
Happy to know that it works. I didn't know that Volca FM was DX7 compatible; I must say that I'm tempted my self :D
