### ISSUE TITLE
Can't load context menu on mac

### ISSUE THREAD

**Issue by dgcohen** [asb2m10/dexed#77]
I'm unable to right-click in the CART window to send a patch to an external device on Mac (using ctrl-click). I've tested this using the AU plug in both Ableton and Logic.

**Comment by asb2m10** [comment]
The ctrl-click seems to be issue; I wasn't able to select anything with it on my side too. But I do have a secondary-click enable (check OS X Preferences/Trackpad) on my MacBook and it works as design. Are you using a old mouse/trackpad with only one button ?

**Comment by dgcohen** [comment]
I'm just using my laptop's trackpad, I can try setting up secondary click when I get home, but it ctl-click would be nice, since this is the only program i use that would require secondary click to be on.
