### ISSUE TITLE
Send entire patch via Sysex

### ISSUE THREAD

**Issue by WouterVanNifterick** [asb2m10/dexed#78]
Hi, I've tried using Dexed as an editor for the FS1R.

The FS1R loads DX7 voices, but it doesn't respond to single-parameter sysex messages.
So I can an entire patch via the cart menu, rightclick on a patch and choose "send program to DX7".

It would be nice if instead of a single parameter, the entire patch could be sent, or that there was at least a button or shortcut.

Or if the feature already exist then maybe it should be less hidden. :)

**Comment by asb2m10** [comment]
Please try the beta build (0.9.2b1) of the next version that should fix that : http://le-son666.com/software/dexed/

I don't have a DX7 with me right now and once the sysex fix works, I'll make it as an official release.
