### ISSUE TITLE
build fails on Fedora 24

### ISSUE THREAD

**Issue by DrPyser** [asb2m10/dexed#81]
When I try to do `make CONFIG=Release`(following instructions from the wiki), the build fails with

`../../JuceLibraryCode/modules/juce_audio_plugin_client/VST/juce_VST_Wrapper.cpp:81:51: fatal error: public.sdk/source/vst2.x/audioeffectx.h: No such file or directory`

I'm setting the srcdir to `/home/drpyser/VST3_SDK`(where I extracted the VST3 SDK).

Thanks.

**Comment by Sentinel77** [comment]
If you are using   srcdir=/home/drpyser/VST3_SDK

Then the VST3 SDK folder you extracted should be on your hardrive like this
/home/drpyser/VST3_SDK/VST3 SDK

**Comment by DrPyser** [comment]
Oh, okay. Thanks.
