### ISSUE TITLE
Sending Sysex as a midi message to Dexed

### ISSUE THREAD

**Issue by fedden** [asb2m10/dexed#87]
Hi there, 

I am writing a Python VST host for usage in deep learning. I have successfully hosted Dexed and made some cool sounds in Python as well as extracted audio features, and now would like to leverage the sysex files obtained from the web, rather than generating my own parameters and setting them in Dexed by using juce::AudioPlugin::setParameter. 

I know sysex can be sent to a hardware DX7 via midi but I was wondering if I could wrap up the sysex files as a juce::midimessage and send them to Dexed to set the current cartrage - I am restricted in the manner I cannot use the GUI! 

Or am I thinking about this wrong?

Sorry also if this is a bad place to get in touch... 

Thanks :)

**Comment by fedden** [comment]
I've tried to give this a go and Dexed doesn't seem to set the the programs upon recieving the sysex midi message.

**Comment by asb2m10** [comment]
Hi,

Dexed doesn't listen to any sysex midi message from the standard plugin midi stream: all of the DAW that I worked with flushes anything that is sysex related. It's the reason why Dexed have it's own configuration midi listener that bind to a specific hardware device to read the sysex data (and there is no JUCE API to call this)... Sorry, blame big names vsthosts :D.

**Comment by fedden** [comment]
Thank you so much for a quick response. If I wanted to load .syx files programmatically whilst avoiding the GUI within the host I have written, can you think of a way of doing so? The only way I can think of is writing an interpreter that takes .syx files and outputs pairs of param indices and param values...

**Comment by asb2m10** [comment]
Or... if you can cast the VSTPlugin instance to a DexedAudioProcessor object, you could use those 2 methods that do that : 

```
void DexedAudioProcessor::handleIncomingMidiMessage(MidiInput* source, const MidiMessage& message) 
 DexedAudioProcessor::updateProgramFromSysex(const uint8_t *rawdata)

```

**Comment by fedden** [comment]
Thanks for the pointers I'll get that implemented :)

**Comment by probonopd** [comment]
@fedden did you ever get this to work? I am looking to automate loading voice data from MiniDexed performances into Dexed instances, #401.
