### ISSUE TITLE
Detune doesn't work like a DX7

### ISSUE THREAD

**Issue by dyacktman** [asb2m10/dexed#88]
Detune is currently implemented as a fixed Hertz increment.  When looking at dx7note.cc, I see the following comment:  "This was measured at 7.213Hz per count at 9600Hz, but the exact value is somewhat dependent on midinote. Close enough for now."

On patches that use detune strategically, this causes detune-based chorusing type effects to be the wrong speed as you move around the keyboard and is a noticeable difference between Dexed and a real DX7.  For reference, watch this video where it is apparent:  https://www.youtube.com/watch?v=FjsJeybu85I   (I didn't make the video, but it did bring this issue to my attention.)

The correct behavior is to detune by cents instead of Hertz.  (ie, the detune amount is relative to the note pitch and not a fixed amount.)

According to the DX7II manual, the range is +/- 2 cents.  So a detune of -7 is -2 cents and a detune of +7 is +2 cents.  I do not know how the values between +/- 1-7 are mapped to the +/- 0-2 cent range and would have to measure a real instrument to determine it, but even a linear interpolation between values would be much better than the current fixed frequency approximation.

Your noted measurement in the comment suggests that the original DX7 might have a different, wider, detuning range than the stated range for a DX7II if I'm understanding it correctly.  (2 cents is a 1.001156 frequency ratio, which would be about +/- 11 Hz at 9600 Hz)  (Those values are based upon the pitch conversion tools here:  http://www.sengpielaudio.com/calculator-centsratio.htm )

It seems to me that improving the implementation of operator detune would be an important change to make for at least the Mark I engine.

**Comment by asb2m10** [comment]
Thanks for documenting this issue ! I will definitely put time to resolve this in the next release.

**Comment by asb2m10** [comment]
I've work on this one and looking with a tuner the DX7 Mark I doesn't seems to work with cents :

MIDI|-7 HZ|-7 CENT|0 HZ|+7 CENT|+7 HZ|INTERVAL
----|-----|-------|----|-------|-----|--------
24|32.4||32.7||33|
36|64.9|-12.5|65.4|12.9|65.9|1
48|130|-10.6|130.8|10.5|131.6|1.6
60|260.2|-9.4|261.6|9.2|263|2.8
72|521.2|-6.9|523.2|7.4|525.5|4.3
84|1044|-4.4|1046|4.9|1049|5
96|2090|-2.4|2093|2.5|2096|6

I did a formula that builds up based on those numbers. It is not the perfect implementation but better than a fix value, for now.
