### ISSUE TITLE
Parameter edit on the DX7 is not received

### ISSUE THREAD

**Issue by AndreaPro** [asb2m10/dexed#94]
I've noticed that SysEx messages are sent from the plugin if I move a parameter and updated correctly on the DX7 but not the other way around,  but sending an entire patch to Dexed via SysEx works, so probably it was meant to work in this way but I think that it should be useful to have a bidirectional update of parameters between the plugin and the DX7. It could be doable?

**Comment by asb2m10** [comment]
Hi,

The DX7 doesn't send the SysEx message at each parameter move. It will send it tough if you press the parameter you changed button.

For example, switch to Algo, move the algo from 1 to 31. No SysEx will be send. But if you press again on the Algo button, the Algo SysEx will be sent.

**Comment by AndreaPro** [comment]
Thank you for the hint. Right now I don't have the DX7 at hand, in the manual the SysEx message is the same when sent and received. I've tried sending back the same SysEx that Dexed sends out when moving a parameter but nothing changes. Am I missing something?

**Comment by asb2m10** [comment]
Bidirectional SysEx parameter support has only been supported since 0.9.3; what version are you using ? Otherwise, what is the SysEx message ?

**Comment by AndreaPro** [comment]
I'm sorry, I was using 0.9.2 and I was mislead by the fact that an external MIDI Input port could be selected. Tried the same with 0.9.3 and it works fine.
