### ISSUE TITLE
Dexed Not Showing in Ableton 32bit PC

### ISSUE THREAD

**Issue by Dex808** [asb2m10/dexed#95]
Hi, I have been trying get Dexed to work in Ableton 32bit for PC. Have tried about three different versions of the plugin, but it just won't show in my plugin folder.

Any help would be most appreciated, as really want to give Dexed a try.

Thanks in advance.

**Comment by asb2m10** [comment]
Are you able to load it with [savihost](http://www.hermannseib.com/english/savihost.htm) ?
