### ISSUE TITLE
Can't install on osx 10.12 and Ableton Live 9

### ISSUE THREAD

**Issue by squishylimbs** [asb2m10/dexed#97]
I downloaded and unzipped the folder, moved the contents into Library>Audio>Plug-ins where everyone else lives, rescanned for plug-ins in Ableton, quit, restarted multiple times, tried in the 32 bit version. No dice, it doesn't show up in the VST or AU folder in Ableton.

Any ideas? Would really appreciate some direction here. 

Thanks!!!!!

**Comment by asb2m10** [comment]
What macOS version are you using ?

**Comment by squishylimbs** [comment]
I'm using Sierra, 10.12

Emily

**Comment by asb2m10** [comment]
Can you run this on the Terminal (based on where Dexed is installed) : 

cd ~/Library/Audio/Plug-Ins/VST/Dexed.vst/Contents/MacOS
otool -L Dexed
